// lib/ce-requirements/rn-data.ts
// RN continuing education requirements — all 50 states + DC.
//
// ⚠️ EVERY ENTRY IS PRE-FILLED AND UNVERIFIED (lastVerified: null).
// Boards change rules. Before a state's page goes live, verify the entry against
// the board's site, correct anything stale, and set lastVerified to today's date.
// getPublishableRequirements() only returns verified entries, so unverified
// states simply don't get pages yet — verify in any order, launch incrementally.
//
// Verification tip: start with the high-population states (TX, CA, FL, NY, PA,
// IL, OH, GA, NC, MI) — they carry most of the search volume.

import type { StateRequirement } from "./types";

export const RN_REQUIREMENTS: StateRequirement[] = [
  {
    state: "Alabama", stateCode: "AL", slug: "alabama", discipline: "rn",
    requirementType: "hours", contactHours: 24, cycleYears: 2,
    summary: "Alabama RNs must complete 24 contact hours every 2 years.",
    acceptsNationalAccreditation: true,
    boardName: "Alabama Board of Nursing",
    sourceUrl: "https://www.abn.alabama.gov/",
    lastVerified: null,
  },
  {
    state: "Alaska", stateCode: "AK", slug: "alaska", discipline: "rn",
    requirementType: "options", contactHours: 30, cycleYears: 2,
    summary: "Alaska RNs must meet continued competency requirements every 2 years — 30 contact hours of CE is one qualifying option.",
    details: "The board accepts a combination of two of: continuing education, professional nursing activities, or employment/practice hours. Verify the current combination rules.",
    acceptsNationalAccreditation: true,
    boardName: "Alaska Board of Nursing",
    sourceUrl: "https://www.commerce.alaska.gov/web/cbpl/professionallicensing/boardofnursing.aspx",
    lastVerified: null,
  },
  {
    state: "Arizona", stateCode: "AZ", slug: "arizona", discipline: "rn",
    requirementType: "none", contactHours: null, cycleYears: 4,
    summary: "Arizona requires no CE contact hours for RN renewal, but you must show continued competency every 4 years — 960 practice hours in the past 5 years, a recent qualifying nursing degree, or a Board-approved refresher program.",
    details: "Arizona RN and LPN licenses renew every 4 years on or before April 1. There is no contact-hour CE mandate, but under A.A.C. R4-19-312 the Board may not renew a license unless you meet the Practice Requirement, which is satisfied by any one of: at least 960 hours of nursing practice in the 5 years before your application (note the lookback is longer than the 4-year license cycle); completing a nursing education program and earning a degree or advanced practice certificate within the past 5 years (LPN-to-RN, RN-to-BSN, master's and doctoral programs all count); or completing an Arizona Board-approved refresher program. Practice counts broadly — paid or volunteer work as a licensed nurse, any position whose job description requires or recommends that level of licensure, and clinical hours completed inside a qualifying degree program. CE contact hours are not an accepted substitute for the practice requirement, so accredited CE will not cure an hours shortfall; a Board-approved refresher program is the path, and the Board can issue a temporary license so you can practice during its clinical portion. Arizona mandates no CE topics for RNs — the 3-hour opioid, substance use disorder or addiction CE under A.R.S. § 32-3248.02 applies only to prescribers holding a DEA registration, which in nursing means APRNs. Late fees apply after May 1 and the license expires August 1; practicing on an expired license violates the Nurse Practice Act. Confirm your own renewal date at Nursys.com or through the Arizona Nurse Portal.",
    acceptsNationalAccreditation: true,
    accreditationNote: "Arizona accepts accredited CE, but no amount of CE satisfies renewal on its own. If you are short of the 960 practice hours, only a Board-approved refresher program — not CE contact hours — restores your eligibility to renew.",
    boardName: "Arizona State Board of Nursing",
    sourceUrl: "https://azbn.gov/licenses-and-certifications/renew-your-license",
    lastVerified: "2026-07-30",
  },
  {
    state: "Arkansas", stateCode: "AR", slug: "arkansas", discipline: "rn",
    requirementType: "options", contactHours: 15, cycleYears: 2,
    summary: "Arkansas RNs must complete 15 practice-focused contact hours every 2 years, or meet an alternative such as national certification.",
    acceptsNationalAccreditation: true,
    boardName: "Arkansas State Board of Nursing",
    sourceUrl: "https://www.healthy.arkansas.gov/programs-services/program/arkansas-state-board-of-nursing",
    lastVerified: null,
  },
  {
    state: "Colorado", stateCode: "CO", slug: "colorado", discipline: "rn",
    requirementType: "none", contactHours: null, cycleYears: null,
    summary: "Colorado has no mandatory CE requirement for RN license renewal.",
    acceptsNationalAccreditation: true,
    boardName: "Colorado Board of Nursing",
    sourceUrl: "https://dpo.colorado.gov/Nursing",
    lastVerified: null,
  },
  {
    state: "Connecticut", stateCode: "CT", slug: "connecticut", discipline: "rn",
    requirementType: "none", contactHours: null, cycleYears: null,
    summary: "Connecticut has no general CE hour requirement for RN renewal.",
    details: "Check for any newer topic-specific mandates before publishing.",
    acceptsNationalAccreditation: true,
    boardName: "Connecticut Board of Examiners for Nursing",
    sourceUrl: "https://portal.ct.gov/dph",
    lastVerified: null,
  },
  {
    state: "Delaware", stateCode: "DE", slug: "delaware", discipline: "rn",
    requirementType: "hours", contactHours: 30, cycleYears: 2,
    summary: "Delaware RNs must complete 30 contact hours every 2 years.",
    mandatoryTopics: [
      { topic: "Substance abuse", hours: 3, frequency: "verify — historically required within the 30 hours" },
    ],
    acceptsNationalAccreditation: true,
    boardName: "Delaware Board of Nursing",
    sourceUrl: "https://dpr.delaware.gov/boards/nursing/",
    lastVerified: null,
  },
  {
    state: "Florida", stateCode: "FL", slug: "florida", discipline: "rn",
    requirementType: "hours", contactHours: 24, cycleYears: 2,
    summary: "Florida RNs must complete 24 contact hours every 2 years — 16 general hours plus state-mandated courses — all reported through CE Broker.",
    mandatoryTopics: [
      { topic: "Prevention of medical errors", hours: 2, frequency: "every renewal; counts within the 24" },
      { topic: "Florida laws and rules", hours: 2, frequency: "every renewal; counts within the 24" },
      { topic: "Recognizing impairment in the workplace", hours: 2, frequency: "every other renewal; counts within the 24" },
      { topic: "Human trafficking", hours: 2, frequency: "every renewal (licenses expiring after Jan 1, 2019); counts within the 24" },
      { topic: "Domestic violence", hours: 2, frequency: "every 3rd renewal — IN ADDITION to the 24 hours" },
      { topic: "HIV/AIDS", hours: 1, frequency: "one-time, before first renewal" },
    ],
    details: "The Board's breakdown is 16 general hours + the mandated topics = 24; domestic violence (every third biennium) is explicitly in addition to the 24. General hours must come from a state or national organization empowered to accredit nursing CE (ANCC-accredited providers qualify); most mandatory-topic courses must be Board-approved (human trafficking is the exception). All CE is reported to the Department of Health via CE Broker — providers report completions there. Nurses first licensed during the current biennium are exempt from general hours but must still complete the mandatory topics. Verify Hiscornerstone's CE Broker reporting before marking Florida live.",
    acceptsNationalAccreditation: true,
    boardName: "Florida Board of Nursing",
    sourceUrl: "https://floridasnursing.gov/registered-nurse-renewal/",
    lastVerified: "2026-07-30",
  },
  {
    state: "Georgia", stateCode: "GA", slug: "georgia", discipline: "rn",
    requirementType: "options", contactHours: 30, cycleYears: 2,
    summary: "Georgia RNs must meet one of five continuing-competency options every 2 years — most commonly 30 contact hours of CE from a board-approved provider.",
    details: "Under Board Rule 410-13-.01 the options are: 30 CE hours from a Board-approved provider; maintenance of certification by a Board-recognized national certifying body; completion of an accredited academic nursing program of study; employer verification of competency plus at least 500 practice hours during the period; or other Board-approved activities. Recognized CE providers include ANCC, ANA, GNA, NLN, and NCSBN; employer-sponsored CE counts for at most 50% of hours unless separately accredited. Licenses renew by January 31 of even-numbered years; CE is reported through CE Broker. Keep documentation at least 4 years.",
    acceptsNationalAccreditation: true,
    boardName: "Georgia Board of Nursing",
    sourceUrl: "https://rules.sos.ga.gov/gac/410-13",
    lastVerified: "2026-07-30",
  },
  {
    state: "Hawaii", stateCode: "HI", slug: "hawaii", discipline: "rn",
    requirementType: "options", contactHours: 30, cycleYears: 2,
    summary: "Hawaii RNs must meet a continued-competency requirement every 2 years — 30 contact hours of CE is one qualifying learning activity.",
    acceptsNationalAccreditation: true,
    boardName: "Hawaii Board of Nursing",
    sourceUrl: "https://cca.hawaii.gov/pvl/boards/nursing/",
    lastVerified: null,
  },
  {
    state: "Idaho", stateCode: "ID", slug: "idaho", discipline: "rn",
    requirementType: "options", contactHours: null, cycleYears: 2,
    summary: "Idaho RNs must complete two learning activities from the board's continued-competency menu every 2 years — CE contact hours qualify.",
    acceptsNationalAccreditation: true,
    boardName: "Idaho Board of Nursing",
    sourceUrl: "https://ibn.idaho.gov/",
    lastVerified: null,
  },
  {
    state: "Illinois", stateCode: "IL", slug: "illinois", discipline: "rn",
    requirementType: "hours", contactHours: 20, cycleYears: 2,
    summary: "Illinois RNs must complete 20 hours of approved continuing education every 2 years, with state-mandated one-hour courses that all count within the 20.",
    mandatoryTopics: [
      { topic: "Sexual harassment prevention", hours: 1, frequency: "every renewal; counts within the 20" },
      { topic: "Implicit bias awareness", hours: 1, frequency: "every renewal; counts within the 20" },
      { topic: "Alzheimer's disease and other dementias", hours: 1, frequency: "once before the first CE renewal, then every 6 years — only for nurses with direct patient interaction with adults 26+; counts within the 20" },
      { topic: "Cultural competency", hours: 1, frequency: "once before the first CE renewal, then every 6 years (renewals on or after Jan 1, 2025); counts within the 20" },
    ],
    details: "RN licenses expire May 31 of even-numbered years (IDFPR extended the 2026 deadline to June 30, 2026). Accepted CE includes ANCC-accredited or approved providers, providers approved by another state's board of nursing, IDFPR-licensed CE sponsors, and accredited universities. Nurses who work with children also complete DCFS mandated reporter training every 6 years (attested at renewal). The 3-hour safe opioid prescribing CE applies to prescribers renewing a Controlled Substances registration, not RNs.",
    acceptsNationalAccreditation: true,
    boardName: "Illinois Department of Financial and Professional Regulation (Board of Nursing)",
    sourceUrl: "https://idfpr.illinois.gov/dpr/continuing-education.html",
    lastVerified: "2026-07-30",
  },
  {
    state: "Indiana", stateCode: "IN", slug: "indiana", discipline: "rn",
    requirementType: "none", contactHours: null, cycleYears: null,
    summary: "Indiana has no mandatory CE requirement for RN license renewal.",
    acceptsNationalAccreditation: true,
    boardName: "Indiana State Board of Nursing",
    sourceUrl: "https://www.in.gov/pla/professions/nursing-home/",
    lastVerified: null,
  },
  {
    state: "Iowa", stateCode: "IA", slug: "iowa", discipline: "rn",
    requirementType: "hours", contactHours: 36, cycleYears: 3,
    summary: "Iowa RNs must complete 36 contact hours every 3 years.",
    mandatoryTopics: [
      { topic: "Dependent adult abuse / child abuse identification", hours: 2, frequency: "every 5 years, if serving those populations — verify" },
    ],
    acceptsNationalAccreditation: true,
    boardName: "Iowa Board of Nursing",
    sourceUrl: "https://nursing.iowa.gov/",
    lastVerified: null,
  },
  {
    state: "Kansas", stateCode: "KS", slug: "kansas", discipline: "rn",
    requirementType: "hours", contactHours: 30, cycleYears: 2,
    summary: "Kansas RNs must complete 30 contact hours of approved continuing nursing education during each 2-year licensing period.",
    details: "Per K.S.A. 65-1117 and K.A.R. 60-9-105/106/107. No mandatory topics. First-renewal exemption: no CNE required if the license expires within 30 months of initial licensure by examination, or within 9 months of licensure by endorsement or reinstatement. Accepted CNE includes providers approved by KSBN, by other state boards of nursing, or by national nursing credentialing associations (ANCC-accredited providers qualify); 1 college credit hour = 15 contact hours; online and independent-study CE count when offered by an approved provider.",
    acceptsNationalAccreditation: true,
    boardName: "Kansas State Board of Nursing",
    sourceUrl: "https://ksbn.kansas.gov/cnes/",
    lastVerified: "2026-07-30",
  },
  {
    state: "Kentucky", stateCode: "KY", slug: "kentucky", discipline: "rn",
    requirementType: "options", contactHours: 14, cycleYears: 1,
    summary: "Kentucky RNs must earn 14 contact hours each year (annual renewal), or meet an alternative such as national certification.",
    acceptsNationalAccreditation: true,
    boardName: "Kentucky Board of Nursing",
    sourceUrl: "https://kbn.ky.gov/",
    lastVerified: null,
  },
  {
    state: "Louisiana", stateCode: "LA", slug: "louisiana", discipline: "rn",
    requirementType: "options", contactHours: 30, cycleYears: 2,
    summary: "Louisiana RNs renew every 2 years and can meet the continued-competency requirement with 30 board-approved contact hours, 900 verified practice hours, or a board-recognized national specialty certification.",
    details: "Per LAC 46:XLVII §3335.C, RNs complete ONE of the following during the 2-year licensure period (licenses expire January 31): 30 board-approved contact hours of CE; 900 practice hours verified by the employer; current national certification in a nursing specialty recognized by the board; or academic credit from a post-secondary nursing program (1 semester hour = 15 contact hours). RNs initially licensed during the previous calendar year are exempt at their first renewal. CE must be approved by a U.S. state board of nursing or ANCC-accredited.",
    acceptsNationalAccreditation: true,
    boardName: "Louisiana State Board of Nursing",
    sourceUrl: "https://www.lsbn.state.la.us/continuing-education-2/",
    lastVerified: "2026-07-30",
  },
  {
    state: "Maine", stateCode: "ME", slug: "maine", discipline: "rn",
    requirementType: "none", contactHours: null, cycleYears: null,
    summary: "Maine has no mandatory CE requirement for RN license renewal.",
    acceptsNationalAccreditation: true,
    boardName: "Maine State Board of Nursing",
    sourceUrl: "https://www.maine.gov/boardofnursing/",
    lastVerified: null,
  },
  {
    state: "Maryland", stateCode: "MD", slug: "maryland", discipline: "rn",
    requirementType: "none", contactHours: null, cycleYears: null,
    summary: "Maryland has no CE hour mandate for RN renewal; continued competency is attested at renewal.",
    acceptsNationalAccreditation: true,
    boardName: "Maryland Board of Nursing",
    sourceUrl: "https://mbon.maryland.gov/",
    lastVerified: null,
  },
  {
    state: "Massachusetts", stateCode: "MA", slug: "massachusetts", discipline: "rn",
    requirementType: "hours", contactHours: 15, cycleYears: 2,
    summary: "Massachusetts RNs must complete 15 contact hours every 2 years, renewing on their birthday in even-numbered years — with no CE required for their very first renewal.",
    mandatoryTopics: [
      { topic: "Cognitive impairment, including Alzheimer's disease and dementia", frequency: "one-time; counts within the 15. Applies to RNs who serve adult populations. No set number of hours." },
      { topic: "Domestic violence and sexual violence training", frequency: "one-time, as a condition of renewal. No set number of hours, and the board has not stated whether it counts within the 15." },
    ],
    details: "RN licenses expire at 11:59 PM on your birthday in even-numbered years (LPNs renew in odd-numbered years), and the 15 contact hours must fall in the two years immediately preceding renewal under 244 CMR 5.02. Nurses renewing for the first time after initial licensure are exempt — the board states plainly that you do not have to complete any CE requirements for your first renewal — and nurses in active military service within 90 days of a renewal deadline are excused for that cycle. Beyond the 15 hours, Massachusetts imposes two one-time trainings. A course on the diagnosis, treatment and care of patients with cognitive impairments including Alzheimer's disease and dementia is required by M.G.L. c. 112 § 74 for RNs who serve adult populations, and the statute folds it into the CE requirement rather than adding it on top. A domestic violence and sexual violence course is separately required as a condition of licensure and renewal under 244 CMR 8.07; once completed you need not repeat it, and the board has not published an hour value or said whether it offsets the 15. Neither training has a board-specified number of hours. Massachusetts has no CE mandate in implicit bias, cultural competency, human trafficking or end-of-life care, and the opioid training under M.G.L. c. 94C § 18(e) applies only to nurses who prescribe controlled substances. Keep authenticated completion records for two consecutive registration periods — four years — and produce them if the board audits you.",
    acceptsNationalAccreditation: true,
    accreditationNote: "Massachusetts runs no CE provider-approval program at all. The board does not maintain a list of approved CE programs and makes each nurse responsible for choosing one that meets the criteria in 244 CMR 5.04, so nationally accredited coursework needs no separate Massachusetts approval. Employer in-services, new-employee orientation, agency policy training and CPR recertification never count.",
    boardName: "Massachusetts Board of Registration in Nursing",
    sourceUrl: "https://www.mass.gov/info-details/mandatory-continuing-education-for-nurses",
    lastVerified: "2026-07-30",
  },
  {
    state: "Michigan", stateCode: "MI", slug: "michigan", discipline: "rn",
    requirementType: "hours", contactHours: 25, cycleYears: 2,
    summary: "Michigan RNs must complete 25 hours of board-approved continuing education every 2 years, including 2 hours in pain and symptom management and 2 hours of implicit bias training per renewal, plus one-time human trafficking training.",
    mandatoryTopics: [
      { topic: "Pain and pain symptom management", hours: 2, frequency: "every renewal; counts within the 25" },
      { topic: "Implicit bias training", hours: 2, frequency: "every renewal (1 hour per year of the 2-year cycle); may count within the 25. New licensees instead need 2 hours within the 5 years before initial licensure" },
      { topic: "Human trafficking victim identification", frequency: "one-time (no minimum hours specified)" },
    ],
    details: "Accepted CE includes programs approved by ANCC, NLN, NAPNES, AANP, AANA, ACNM, ACCME, AMA, AOA, other state or provincial boards of nursing, and board-approved providers. Nurses initially licensed on or after May 8, 2024 must complete CE for their first renewal.",
    acceptsNationalAccreditation: true,
    boardName: "Michigan Board of Nursing (LARA Bureau of Professional Licensing)",
    sourceUrl: "https://www.michigan.gov/lara/-/media/Project/Websites/lara/bpl/Nursing/Licensing-Info-and-Forms/Nursing-Licensing-Guide-FAQ-12626.pdf",
    lastVerified: "2026-07-30",
  },
  {
    state: "Minnesota", stateCode: "MN", slug: "minnesota", discipline: "rn",
    requirementType: "hours", contactHours: 24, cycleYears: 2,
    summary: "Minnesota RNs must complete 24 contact hours every 2 years.",
    acceptsNationalAccreditation: true,
    boardName: "Minnesota Board of Nursing",
    sourceUrl: "https://mn.gov/boards/nursing/",
    lastVerified: null,
  },
  {
    state: "Mississippi", stateCode: "MS", slug: "mississippi", discipline: "rn",
    requirementType: "none", contactHours: null, cycleYears: null,
    summary: "Mississippi has no general CE hour mandate for RN renewal.",
    details: "Verify — Mississippi has considered CE mandates; check current board rules before publishing.",
    acceptsNationalAccreditation: true,
    boardName: "Mississippi Board of Nursing",
    sourceUrl: "https://www.msbn.ms.gov/",
    lastVerified: null,
  },
  {
    state: "Missouri", stateCode: "MO", slug: "missouri", discipline: "rn",
    requirementType: "none", contactHours: null, cycleYears: null,
    summary: "Missouri has no mandatory CE requirement for RN license renewal.",
    acceptsNationalAccreditation: true,
    boardName: "Missouri State Board of Nursing",
    sourceUrl: "https://pr.mo.gov/nursing.asp",
    lastVerified: null,
  },
  {
    state: "Montana", stateCode: "MT", slug: "montana", discipline: "rn",
    requirementType: "hours", contactHours: 24, cycleYears: 2,
    summary: "Montana RNs must complete 24 contact hours every 2 years.",
    acceptsNationalAccreditation: true,
    boardName: "Montana Board of Nursing",
    sourceUrl: "https://boards.bsd.dli.mt.gov/nursing/",
    lastVerified: null,
  },
  {
    state: "Nebraska", stateCode: "NE", slug: "nebraska", discipline: "rn",
    requirementType: "hours", contactHours: 20, cycleYears: 2,
    summary: "Nebraska RNs must complete 20 contact hours every 2 years.",
    acceptsNationalAccreditation: true,
    boardName: "Nebraska Board of Nursing (DHHS)",
    sourceUrl: "https://dhhs.ne.gov/licensure/Pages/Nurse-Licensing.aspx",
    lastVerified: null,
  },
  {
    state: "Nevada", stateCode: "NV", slug: "nevada", discipline: "rn",
    requirementType: "hours", contactHours: 30, cycleYears: 2,
    summary: "Nevada RNs must complete 30 contact hours every 2 years, including mandated topics.",
    mandatoryTopics: [
      { topic: "Bioterrorism / weapons of mass destruction", hours: 4, frequency: "one-time" },
      { topic: "Cultural competency / diversity, equity and inclusion", frequency: "every renewal — verify hours" },
      { topic: "Suicide prevention", frequency: "verify — required for some license types" },
    ],
    acceptsNationalAccreditation: true,
    boardName: "Nevada State Board of Nursing",
    sourceUrl: "https://nevadanursingboard.org/",
    lastVerified: null,
  },
  {
    state: "New Hampshire", stateCode: "NH", slug: "new-hampshire", discipline: "rn",
    requirementType: "hours", contactHours: 30, cycleYears: 2,
    summary: "New Hampshire RNs must complete 30 contact hours every 2 years.",
    acceptsNationalAccreditation: true,
    boardName: "New Hampshire Board of Nursing",
    sourceUrl: "https://www.oplc.nh.gov/board-nursing",
    lastVerified: null,
  },
  {
    // HOLD — do not set lastVerified until the two board pages below are opened by hand.
    // N.J.A.C. 13:37-5.3 text is HIGH confidence (two independent verbatim-matching
    // reproductions), but njconsumeraffairs.gov returns 403 to every automated fetcher,
    // so the board's own CE page was never read, and a bias-training rule proposed
    // 2024-07-15 for perinatal providers may have been adopted since. Check:
    //   https://www.njconsumeraffairs.gov/nur/pages/continuingeducation.aspx
    //   https://www.njconsumeraffairs.gov/nur/pages/continuing-education-faq.aspx
    state: "New Jersey", stateCode: "NJ", slug: "new-jersey", discipline: "rn",
    requirementType: "hours", contactHours: 30, cycleYears: 2,
    summary: "New Jersey RNs must complete 30 contact hours every 2 years, including at least 1 hour on prescription opioid drugs.",
    mandatoryTopics: [
      { topic: "Prescription opioid drugs — including alternatives for managing pain and the risks and signs of opioid abuse, addiction and diversion", hours: 1, frequency: "every renewal; counts within the 30" },
    ],
    details: "The 30 hours are required of both registered professional nurses and licensed practical nurses during each biennial renewal period, and you attest to completion at renewal (N.J.A.C. 13:37-5.3). At least one of the 30 must address prescription opioid drugs — the rule says the 30 hours shall include that hour, so it is not an extra hour on top. If you complete more than 30 hours in a period you may carry up to 15 of the extra hours into the next biennium. Separately, a one-time one-credit-hour course on organ and tissue donation and recovery is required by statute (N.J.S.A. 45:11-26.1) as a condition of relicensure, but only for nurses licensed in New Jersey before the 2008 Hero Act who did not receive that instruction as part of their nursing program — nurses whose curriculum covered it are not subject to it, which is most nurses educated in New Jersey since roughly 2011. Vendors often market this as a universal recurring New Jersey requirement; it is not. Advanced practice nurses must meet the RN 30 hours plus their national certifying agency's CE, including two credits in end-of-life care.",
    acceptsNationalAccreditation: true,
    accreditationNote: "N.J.A.C. 13:37-5.3(d)(2) awards credit for courses approved by, or offered by entities accredited by, the American Nurses Credentialing Center, and 13:37-5.3(d)(1) independently covers NCCA-accredited and IACET Authorized Provider courses. There is no separate New Jersey provider approval number. A single course counts only once even if it qualifies under more than one category.",
    boardName: "New Jersey Board of Nursing",
    sourceUrl: "https://www.njconsumeraffairs.gov/nur/pages/continuingeducation.aspx",
    lastVerified: null,
  },
  {
    state: "New Mexico", stateCode: "NM", slug: "new-mexico", discipline: "rn",
    requirementType: "hours", contactHours: 30, cycleYears: 2,
    summary: "New Mexico RNs must complete 30 contact hours every 2 years.",
    acceptsNationalAccreditation: true,
    boardName: "New Mexico Board of Nursing",
    sourceUrl: "https://www.bon.nm.gov/",
    lastVerified: null,
  },
  {
    state: "North Carolina", stateCode: "NC", slug: "north-carolina", discipline: "rn",
    requirementType: "options", contactHours: 30, cycleYears: 2,
    summary: "North Carolina RNs must complete one of eight continuing-competence options every 2 years — such as 30 contact hours of CE, or 15 contact hours combined with 640 hours of active practice.",
    details: "Under 21 NCAC 36 .0232 the options include: 30 contact hours of CE; national certification by a Board-recognized credentialing body; 15 contact hours plus 640 practice hours within the previous 2 years; a Board-approved refresher course; 2+ semester hours of post-licensure academic education; or 15 contact hours plus a nursing project, publication, or CE presentation. Acceptable CE providers include ANCC, ANA, NCNA, NLN, NCSBN, and any state board of nursing; employer-sponsored CE is capped at 50% unless separately accredited. Licenses renew every 2 years by the last day of the nurse's birth month; evidence is submitted only if audited (keep documentation 3 years).",
    acceptsNationalAccreditation: true,
    boardName: "North Carolina Board of Nursing",
    sourceUrl: "https://www.ncbon.com/licensure-listing-continuing-competence",
    lastVerified: "2026-07-30",
  },
  {
    state: "North Dakota", stateCode: "ND", slug: "north-dakota", discipline: "rn",
    requirementType: "none", contactHours: null, cycleYears: null,
    summary: "North Dakota has no mandatory CE hour requirement for RN renewal.",
    details: "Verify — ND has practice-hour requirements for renewal; confirm current continued-competency rules.",
    acceptsNationalAccreditation: true,
    boardName: "North Dakota Board of Nursing",
    sourceUrl: "https://www.ndbon.org/",
    lastVerified: null,
  },
  {
    state: "Ohio", stateCode: "OH", slug: "ohio", discipline: "rn",
    requirementType: "hours", contactHours: 24, cycleYears: 2,
    summary: "Ohio RNs must complete 24 contact hours of continuing education every 2-year renewal period, including at least 1 hour of Category A content covering Ohio nursing law and rules.",
    mandatoryTopics: [
      { topic: "Category A: Ohio nursing law and rules (Chapter 4723)", hours: 1, frequency: "every renewal; counts within the 24; must be approved by the board, an OBN approver, or a nationally accredited provider" },
    ],
    details: "RN licenses renew in odd-numbered years (application due September 15; unrenewed licenses expire November 1). The CE reporting period runs July 1 through June 30 of odd years. No CE is required for the first renewal after licensure by examination; nurses licensed by endorsement for a year or less need only 12 hours. CE approved by ANCC or another nationally recognized accreditation system, another state's board, or an OBN approver all count.",
    acceptsNationalAccreditation: true,
    boardName: "Ohio Board of Nursing",
    sourceUrl: "https://codes.ohio.gov/ohio-administrative-code/rule-4723-14-03",
    lastVerified: "2026-07-30",
  },
  {
    state: "Oklahoma", stateCode: "OK", slug: "oklahoma", discipline: "rn",
    requirementType: "options", contactHours: 24, cycleYears: 2,
    summary: "Oklahoma RNs must meet one of several competency options every 2 years — 24 contact hours of CE is one qualifying path.",
    details: "Alternatives include national certification and verified practice hours.",
    acceptsNationalAccreditation: true,
    boardName: "Oklahoma Board of Nursing",
    sourceUrl: "https://oklahoma.gov/nursing.html",
    lastVerified: null,
  },
  {
    state: "Oregon", stateCode: "OR", slug: "oregon", discipline: "rn",
    requirementType: "none", contactHours: null, cycleYears: null,
    summary: "Oregon has no recurring CE hour mandate for RNs; a one-time pain management course is required.",
    mandatoryTopics: [
      { topic: "Pain management (Oregon Pain Management Commission module + related coursework)", hours: 7, frequency: "one-time — verify current hours" },
    ],
    acceptsNationalAccreditation: true,
    boardName: "Oregon State Board of Nursing",
    sourceUrl: "https://www.oregon.gov/osbn/",
    lastVerified: null,
  },
  {
    state: "Pennsylvania", stateCode: "PA", slug: "pennsylvania", discipline: "rn",
    requirementType: "hours", contactHours: 30, cycleYears: 2,
    summary: "Pennsylvania RNs must complete 30 hours of Board-approved continuing education every 2 years, including 2 hours of child abuse recognition training and, effective May 1, 2026, a one-time 2-hour organ and tissue donation course.",
    mandatoryTopics: [
      { topic: "Child abuse recognition and reporting (Act 31, DHS-approved provider)", hours: 2, frequency: "every renewal; counts within the 30; required even at the otherwise CE-exempt first renewal" },
      { topic: "Organ and tissue donation and recovery process", hours: 2, frequency: "one-time, within 5 years of initial licensure or of a renewal (effective May 1, 2026)" },
    ],
    details: "Required by Act 58 of 2006 and 49 Pa. Code § 21.131. First-time licensees are exempt from the 30 hours at their first renewal except the child abuse training. Hours cannot carry over between periods. The Board accepts CE from national nursing organizations, accredited nursing programs and health care facilities, regionally accredited colleges, and providers approved by other states' boards — ANCC-accredited provider CE is accepted under these categories. Opioid CE applies to prescribers only, not RNs.",
    acceptsNationalAccreditation: true,
    boardName: "Pennsylvania State Board of Nursing",
    sourceUrl: "https://www.pa.gov/agencies/dos/department-and-offices/bpoa/boards-commissions/nursing/registered-nurses-licensure-snapshot",
    lastVerified: "2026-07-30",
  },
  {
    state: "Rhode Island", stateCode: "RI", slug: "rhode-island", discipline: "rn",
    requirementType: "hours", contactHours: 10, cycleYears: 2,
    summary: "Rhode Island RNs must complete 10 contact hours every 2 years.",
    mandatoryTopics: [
      { topic: "Substance abuse", frequency: "verify — historically required within the total" },
    ],
    acceptsNationalAccreditation: true,
    boardName: "Rhode Island Board of Nurse Registration and Nursing Education",
    sourceUrl: "https://health.ri.gov/licenses/detail.php?id=231",
    lastVerified: null,
  },
  {
    state: "South Carolina", stateCode: "SC", slug: "south-carolina", discipline: "rn",
    requirementType: "options", contactHours: 30, cycleYears: 2,
    summary: "South Carolina RNs must meet one of several competency options every 2 years — 30 contact hours of CE is one qualifying path.",
    details: "Alternatives include national certification, academic coursework, or employer-verified practice hours.",
    acceptsNationalAccreditation: true,
    boardName: "South Carolina Board of Nursing (LLR)",
    sourceUrl: "https://llr.sc.gov/nurse/",
    lastVerified: null,
  },
  {
    state: "South Dakota", stateCode: "SD", slug: "south-dakota", discipline: "rn",
    requirementType: "none", contactHours: null, cycleYears: null,
    summary: "South Dakota has no mandatory CE requirement for RN renewal (practice-hour requirements apply instead).",
    acceptsNationalAccreditation: true,
    boardName: "South Dakota Board of Nursing",
    sourceUrl: "https://doh.sd.gov/boards/nursing/",
    lastVerified: null,
  },
  {
    state: "Tennessee", stateCode: "TN", slug: "tennessee", discipline: "rn",
    requirementType: "options", contactHours: null, cycleYears: 2,
    summary: "Tennessee RNs must demonstrate continued competence every 2 years through options that can include continuing education, practice hours, or certification.",
    acceptsNationalAccreditation: true,
    boardName: "Tennessee Board of Nursing",
    sourceUrl: "https://www.tn.gov/health/health-program-areas/health-professional-boards/nursing-board.html",
    lastVerified: null,
  },
  {
    state: "Texas", stateCode: "TX", slug: "texas", discipline: "rn",
    requirementType: "options", contactHours: 20, cycleYears: 2,
    summary: "Texas RNs must complete 20 contact hours of continuing education in their area of practice every 2 years, or instead hold a Board-approved national certification — plus targeted courses that apply based on where and how they practice.",
    details: "Board Rule 216.3 allows either 20 contact hours in your area of practice or achieving/maintaining/renewing a Board-approved national certification. Certification can NOT substitute for the nursing jurisprudence and ethics requirement, and the human trafficking prevention course (required for nurses providing direct patient care) must come from the HHSC executive commissioner's approved course list. Targeted-topic hours count within the 20, not on top of it.",
    mandatoryTopics: [
      { topic: "Nursing jurisprudence and ethics", hours: 2, frequency: "every third two-year licensing period; counts within the 20 hours; cannot be met by certification" },
      { topic: "Human trafficking prevention (HHSC-approved course)", frequency: "every renewal, for nurses providing direct patient care" },
      { topic: "Older adult / geriatric care", hours: 2, frequency: "every renewal, if your practice includes older adult or geriatric populations; counts within the 20 hours" },
      { topic: "Forensic evidence collection", hours: 2, frequency: "one-time, for nurses practicing in an emergency room setting (within 2 years of beginning ER practice)" },
    ],
    acceptsNationalAccreditation: true,
    boardName: "Texas Board of Nursing",
    sourceUrl: "https://www.bon.texas.gov/education_continuing_education.asp.html",
    lastVerified: "2026-07-30",
  },
  {
    state: "Utah", stateCode: "UT", slug: "utah", discipline: "rn",
    requirementType: "options", contactHours: 30, cycleYears: 2,
    summary: "Utah RNs must meet continued-competency requirements every 2 years — CE hours scale with practice hours (e.g. 30 CE hours if practicing fewer than 200 hours; 15 CE hours with 200–399 practice hours; none with 400+).",
    details: "Verify the current practice-hour tiers.",
    acceptsNationalAccreditation: true,
    boardName: "Utah Division of Professional Licensing — Board of Nursing",
    sourceUrl: "https://dopl.utah.gov/nurse/",
    lastVerified: null,
  },
  {
    state: "Vermont", stateCode: "VT", slug: "vermont", discipline: "rn",
    requirementType: "none", contactHours: null, cycleYears: null,
    summary: "Vermont has no CE hour mandate for RN renewal (practice-hour requirements apply instead).",
    acceptsNationalAccreditation: true,
    boardName: "Vermont Board of Nursing",
    sourceUrl: "https://sos.vermont.gov/nursing/",
    lastVerified: null,
  },
  {
    state: "Virginia", stateCode: "VA", slug: "virginia", discipline: "rn",
    requirementType: "options", contactHours: 30, cycleYears: 2,
    summary: "Virginia RNs must satisfy one of nine continued-competency options every 2 years — 30 contact hours of CE is the most common path, or 15 contact hours plus 640 hours of active practice.",
    details: "Virginia does not impose a flat CE requirement. Under 18VAC90-19-160 you must complete at least one of nine qualifying activities each renewal cycle: hold current specialty certification from a national certifying organization; complete at least three credit hours of post-licensure academic coursework relevant to nursing at a regionally accredited college or university; complete a board-approved refresher course; complete a nursing-related evidence-based practice project or research study; publish as author or co-author during the cycle; teach or develop a nursing-related course worth at least three semester hours, a 15-week course, or specialty certification; teach or develop nursing CE courses for up to 30 contact hours; complete 15 contact hours plus 640 hours of active nursing practice; or complete 30 contact hours. A contact hour in Virginia is 50 minutes. Licenses renew biennially by the last day of your birth month, in even-numbered years if you were born in an even-numbered year and odd-numbered years if you were born in an odd-numbered year — so your renewal year follows your birth year, not a fixed schedule. You are exempt from continued competency for your first renewal after initial licensure by exam or endorsement. RNs who also hold an active nurse practitioner license follow 18VAC90-30-105 instead (plus 18VAC90-40-55 with prescriptive authority). Keep your documentation for two years after renewal and produce it within 30 days if the board audits you. Virginia currently mandates no specific CE subject for RNs, though the 2026 General Assembly directed the board to adopt a bias-reduction training requirement of up to two hours, counted within the existing total; that rule is not yet in effect and the board has not amended 18VAC90-19-160 or designated a subject area.",
    acceptsNationalAccreditation: true,
    accreditationNote: "For the contact-hour pathways, 18VAC90-19-160(B) lists thirteen recognized approvers, and the American Nurses Credentialing Center is first among them. Virginia runs no separate state provider-approval program, so ANCC-accredited coursework needs no additional Virginia approval.",
    boardName: "Virginia Board of Nursing",
    sourceUrl: "https://www.dhp.virginia.gov/Boards/Nursing/PractitionerResources/ContinuedCompetency/RNLPN/",
    lastVerified: "2026-07-30",
  },
  {
    state: "Washington", stateCode: "WA", slug: "washington", discipline: "rn",
    requirementType: "hours", contactHours: 8, cycleYears: 1,
    summary: "Washington RNs renew every year on their birthday and must complete 8 contact hours of continuing education plus 96 hours of active nursing practice in the preceding 12 months.",
    mandatoryTopics: [
      { topic: "Health equity", hours: 2, frequency: "every year, at every renewal; counts within the 8" },
      { topic: "Suicide assessment, treatment and management", hours: 6, frequency: "one-time, by the end of your first full year of licensure; counts within the 8. CRNAs are exempt. Must come from a Washington DOH Model List program." },
      { topic: "Telemedicine training", frequency: "one-time, and only for nurses providing clinical services by telemedicine. No hour count is set by statute or rule." },
    ],
    details: "Washington moved to an annual cycle in June 2021, so the older 24-or-45-hour multi-year figures still circulating online are out of date. Your license expires on your birthday every year, and at each renewal you attest that you completed at least 8 hours of continuing nursing education and at least 96 hours of active nursing practice during the preceding 12 months (WAC 246-840-220). Hours cannot be rolled over from one year to the next. Active nursing practice is defined broadly — paid, unpaid or volunteer work requiring substantial nursing knowledge, judgment and skill, including administrator, quality manager, policy, educator, consultant and regulator roles, not just direct care. Two of your 8 hours must be health equity training every single year; that counts inside the 8, and while the course need not come from a state list it must meet the content standards in WAC 246-12-830, including implicit bias content and either an end-of-course assessment or an attendance attestation. Separately, every RN except those holding an active CRNA license must complete a one-time 6-hour training in suicide assessment, treatment and management by the end of their first full year of licensure; it also counts inside the 8, but it must come from a program on the Washington Department of Health Model List. Nurses who deliver clinical services by telemedicine must additionally complete training under RCW 43.70.495 and retain a signed attestation. Nurses enrolled in an advanced nursing education program are exempt from continuing competency for that review period. Note that the 30 CE hours plus 15 pharmacology hours often cited for Washington apply to ARNPs on a two-year cycle, not to RNs.",
    acceptsNationalAccreditation: true,
    accreditationNote: "Washington requires no formal accreditation for general CE — the Board of Nursing states that the laws and rules do not require continuing education hours to have formal CEUs or CNEs, so accredited coursework qualifies but is not mandatory. The exception is the one-time 6-hour suicide prevention training, which must come from a program on the Washington DOH Model List; national accreditation alone does not satisfy that one.",
    boardName: "Washington State Board of Nursing",
    sourceUrl: "https://nursing.wa.gov/licensing/maintain-license/continuing-competency",
    lastVerified: "2026-07-30",
  },
  {
    state: "West Virginia", stateCode: "WV", slug: "west-virginia", discipline: "rn",
    requirementType: "hours", contactHours: 12, cycleYears: 1,
    summary: "West Virginia RNs must complete 12 contact hours each annual reporting period, with periodic mandated topics.",
    mandatoryTopics: [
      { topic: "Substance use disorder / drug diversion", frequency: "verify — periodic mandate" },
      { topic: "Mental health conditions common to veterans", hours: 2, frequency: "one-time — verify" },
    ],
    acceptsNationalAccreditation: true,
    boardName: "West Virginia RN Board",
    sourceUrl: "https://wvrnboard.wv.gov/",
    lastVerified: null,
  },
  {
    state: "Wisconsin", stateCode: "WI", slug: "wisconsin", discipline: "rn",
    requirementType: "none", contactHours: null, cycleYears: null,
    summary: "Wisconsin has no mandatory CE requirement for RN license renewal.",
    acceptsNationalAccreditation: true,
    boardName: "Wisconsin Board of Nursing",
    sourceUrl: "https://dsps.wi.gov/Pages/BoardsCouncils/Nursing/",
    lastVerified: null,
  },
  {
    state: "Wyoming", stateCode: "WY", slug: "wyoming", discipline: "rn",
    requirementType: "options", contactHours: 20, cycleYears: 2,
    summary: "Wyoming RNs must meet continued-competency options every 2 years — contact hours combined with practice hours is a common path.",
    details: "Verify the current option tiers (CE hours vs. practice hours vs. certification).",
    acceptsNationalAccreditation: true,
    boardName: "Wyoming State Board of Nursing",
    sourceUrl: "https://nursing-online.state.wy.us/",
    lastVerified: null,
  },
  {
    state: "Washington, D.C.", stateCode: "DC", slug: "washington-dc", discipline: "rn",
    requirementType: "hours", contactHours: 24, cycleYears: 2,
    summary: "D.C. RNs must complete 24 contact hours every 2 years, including district-mandated topics.",
    mandatoryTopics: [
      { topic: "LGBTQ cultural competency", hours: 2, frequency: "every renewal" },
      { topic: "Public health priorities (per DOH)", frequency: "every renewal — verify current topics" },
    ],
    acceptsNationalAccreditation: true,
    boardName: "District of Columbia Board of Nursing",
    sourceUrl: "https://dchealth.dc.gov/bon",
    lastVerified: null,
  },
];
