// lib/ce-requirements/rn-data.ts
// RN continuing education requirements — all 50 states + DC.
//
// ⚠️ EVERY ENTRY IS PRE-FILLED AND UNVERIFIED (lastVerified: null).
// Boards change rules. Before a state's page goes live, verify the entry against
// the board's site, correct anything stale, and set lastVerified to today's date.
// getPublishableRequirements() only returns verified entries, so unverified
// states simply don't get pages yet — verify in any order, launch incrementally.
//
// Verification tip: start with the high-population states (TX, CA, FL, NY, PA,
// IL, OH, GA, NC, MI) — they carry most of the search volume.

import type { StateRequirement } from "./types";

export const RN_REQUIREMENTS: StateRequirement[] = [
  {
    state: "Alabama", stateCode: "AL", slug: "alabama", discipline: "rn",
    requirementType: "hours", contactHours: 24, cycleYears: 2,
    summary: "Alabama RNs must complete 24 contact hours every 2 years.",
    acceptsNationalAccreditation: true,
    boardName: "Alabama Board of Nursing",
    sourceUrl: "https://www.abn.alabama.gov/",
    lastVerified: null,
  },
  {
    state: "Alaska", stateCode: "AK", slug: "alaska", discipline: "rn",
    requirementType: "options", contactHours: 30, cycleYears: 2,
    summary: "Alaska RNs must meet continued competency requirements every 2 years — 30 contact hours of CE is one qualifying option.",
    details: "The board accepts a combination of two of: continuing education, professional nursing activities, or employment/practice hours. Verify the current combination rules.",
    acceptsNationalAccreditation: true,
    boardName: "Alaska Board of Nursing",
    sourceUrl: "https://www.commerce.alaska.gov/web/cbpl/professionallicensing/boardofnursing.aspx",
    lastVerified: null,
  },
  {
    state: "Arizona", stateCode: "AZ", slug: "arizona", discipline: "rn",
    requirementType: "none", contactHours: null, cycleYears: null,
    summary: "Arizona has no mandatory CE requirement for RN license renewal.",
    details: "RNs renew based on licensure requirements without a contact-hour mandate. Free CE still helps with certifications, compact-state moves, and professional development.",
    acceptsNationalAccreditation: true,
    boardName: "Arizona State Board of Nursing",
    sourceUrl: "https://www.azbn.gov/",
    lastVerified: null,
  },
  {
    state: "Arkansas", stateCode: "AR", slug: "arkansas", discipline: "rn",
    requirementType: "options", contactHours: 15, cycleYears: 2,
    summary: "Arkansas RNs must complete 15 practice-focused contact hours every 2 years, or meet an alternative such as national certification.",
    acceptsNationalAccreditation: true,
    boardName: "Arkansas State Board of Nursing",
    sourceUrl: "https://www.healthy.arkansas.gov/programs-services/program/arkansas-state-board-of-nursing",
    lastVerified: null,
  },
  {
    state: "California", stateCode: "CA", slug: "california", discipline: "rn",
    requirementType: "hours", contactHours: 30, cycleYears: 2,
    summary: "California RNs must complete 30 contact hours every 2 years from a board-approved (CEP) provider.",
    details: "California requires providers to hold a BRN Continuing Education Provider (CEP) number — ANCC accreditation alone may not satisfy the BRN. Confirm Hiscornerstone's CEP status before marking courses as California-accepted.",
    acceptsNationalAccreditation: false,
    boardName: "California Board of Registered Nursing",
    sourceUrl: "https://www.rn.ca.gov/",
    lastVerified: null,
  },
  {
    state: "Colorado", stateCode: "CO", slug: "colorado", discipline: "rn",
    requirementType: "none", contactHours: null, cycleYears: null,
    summary: "Colorado has no mandatory CE requirement for RN license renewal.",
    acceptsNationalAccreditation: true,
    boardName: "Colorado Board of Nursing",
    sourceUrl: "https://dpo.colorado.gov/Nursing",
    lastVerified: null,
  },
  {
    state: "Connecticut", stateCode: "CT", slug: "connecticut", discipline: "rn",
    requirementType: "none", contactHours: null, cycleYears: null,
    summary: "Connecticut has no general CE hour requirement for RN renewal.",
    details: "Check for any newer topic-specific mandates before publishing.",
    acceptsNationalAccreditation: true,
    boardName: "Connecticut Board of Examiners for Nursing",
    sourceUrl: "https://portal.ct.gov/dph",
    lastVerified: null,
  },
  {
    state: "Delaware", stateCode: "DE", slug: "delaware", discipline: "rn",
    requirementType: "hours", contactHours: 30, cycleYears: 2,
    summary: "Delaware RNs must complete 30 contact hours every 2 years.",
    mandatoryTopics: [
      { topic: "Substance abuse", hours: 3, frequency: "verify — historically required within the 30 hours" },
    ],
    acceptsNationalAccreditation: true,
    boardName: "Delaware Board of Nursing",
    sourceUrl: "https://dpr.delaware.gov/boards/nursing/",
    lastVerified: null,
  },
  {
    state: "Florida", stateCode: "FL", slug: "florida", discipline: "rn",
    requirementType: "hours", contactHours: 24, cycleYears: 2,
    summary: "Florida RNs must complete 24 contact hours every 2 years, including several state-mandated topics.",
    mandatoryTopics: [
      { topic: "Prevention of medical errors", hours: 2, frequency: "every renewal" },
      { topic: "Florida laws and rules", hours: 2, frequency: "every renewal" },
      { topic: "Recognizing impairment in the workplace", hours: 2, frequency: "every other renewal — verify" },
      { topic: "Human trafficking", hours: 1, frequency: "one-time — verify" },
      { topic: "Domestic violence", hours: 2, frequency: "every 3rd renewal" },
      { topic: "HIV/AIDS", hours: 1, frequency: "one-time" },
    ],
    details: "Florida uses CE Broker for tracking — providers typically must report there. Verify Hiscornerstone's CE Broker reporting before marking Florida live.",
    acceptsNationalAccreditation: true,
    boardName: "Florida Board of Nursing",
    sourceUrl: "https://floridasnursing.gov/",
    lastVerified: null,
  },
  {
    state: "Georgia", stateCode: "GA", slug: "georgia", discipline: "rn",
    requirementType: "options", contactHours: 30, cycleYears: 2,
    summary: "Georgia RNs must meet one of several competency options every 2 years — 30 contact hours of CE is the most common path.",
    details: "Alternatives include national certification, an accredited academic course, or verified practice hours plus employer attestation.",
    acceptsNationalAccreditation: true,
    boardName: "Georgia Board of Nursing",
    sourceUrl: "https://sos.ga.gov/georgia-board-nursing",
    lastVerified: null,
  },
  {
    state: "Hawaii", stateCode: "HI", slug: "hawaii", discipline: "rn",
    requirementType: "options", contactHours: 30, cycleYears: 2,
    summary: "Hawaii RNs must meet a continued-competency requirement every 2 years — 30 contact hours of CE is one qualifying learning activity.",
    acceptsNationalAccreditation: true,
    boardName: "Hawaii Board of Nursing",
    sourceUrl: "https://cca.hawaii.gov/pvl/boards/nursing/",
    lastVerified: null,
  },
  {
    state: "Idaho", stateCode: "ID", slug: "idaho", discipline: "rn",
    requirementType: "options", contactHours: null, cycleYears: 2,
    summary: "Idaho RNs must complete two learning activities from the board's continued-competency menu every 2 years — CE contact hours qualify.",
    acceptsNationalAccreditation: true,
    boardName: "Idaho Board of Nursing",
    sourceUrl: "https://ibn.idaho.gov/",
    lastVerified: null,
  },
  {
    state: "Illinois", stateCode: "IL", slug: "illinois", discipline: "rn",
    requirementType: "hours", contactHours: 20, cycleYears: 2,
    summary: "Illinois RNs must complete 20 contact hours every 2 years, including state-mandated topics.",
    mandatoryTopics: [
      { topic: "Sexual harassment prevention", hours: 1, frequency: "every renewal" },
      { topic: "Implicit bias awareness", hours: 1, frequency: "every renewal" },
      { topic: "Alzheimer's disease and dementia", hours: 1, frequency: "every renewal — verify applicability" },
    ],
    acceptsNationalAccreditation: true,
    boardName: "Illinois Department of Financial and Professional Regulation",
    sourceUrl: "https://idfpr.illinois.gov/",
    lastVerified: null,
  },
  {
    state: "Indiana", stateCode: "IN", slug: "indiana", discipline: "rn",
    requirementType: "none", contactHours: null, cycleYears: null,
    summary: "Indiana has no mandatory CE requirement for RN license renewal.",
    acceptsNationalAccreditation: true,
    boardName: "Indiana State Board of Nursing",
    sourceUrl: "https://www.in.gov/pla/professions/nursing-home/",
    lastVerified: null,
  },
  {
    state: "Iowa", stateCode: "IA", slug: "iowa", discipline: "rn",
    requirementType: "hours", contactHours: 36, cycleYears: 3,
    summary: "Iowa RNs must complete 36 contact hours every 3 years.",
    mandatoryTopics: [
      { topic: "Dependent adult abuse / child abuse identification", hours: 2, frequency: "every 5 years, if serving those populations — verify" },
    ],
    acceptsNationalAccreditation: true,
    boardName: "Iowa Board of Nursing",
    sourceUrl: "https://nursing.iowa.gov/",
    lastVerified: null,
  },
  {
    state: "Kansas", stateCode: "KS", slug: "kansas", discipline: "rn",
    requirementType: "hours", contactHours: 30, cycleYears: 2,
    summary: "Kansas RNs must complete 30 contact hours every 2 years.",
    acceptsNationalAccreditation: true,
    boardName: "Kansas State Board of Nursing",
    sourceUrl: "https://ksbn.kansas.gov/",
    lastVerified: null,
  },
  {
    state: "Kentucky", stateCode: "KY", slug: "kentucky", discipline: "rn",
    requirementType: "options", contactHours: 14, cycleYears: 1,
    summary: "Kentucky RNs must earn 14 contact hours each year (annual renewal), or meet an alternative such as national certification.",
    acceptsNationalAccreditation: true,
    boardName: "Kentucky Board of Nursing",
    sourceUrl: "https://kbn.ky.gov/",
    lastVerified: null,
  },
  {
    state: "Louisiana", stateCode: "LA", slug: "louisiana", discipline: "rn",
    requirementType: "hours", contactHours: 15, cycleYears: 1,
    summary: "Louisiana RNs complete 5–15 contact hours annually, scaled by practice hours worked.",
    details: "Full-time practice = 5 hours, part-time = 10, not practicing = 15. Verify the current tiers.",
    acceptsNationalAccreditation: true,
    boardName: "Louisiana State Board of Nursing",
    sourceUrl: "https://www.lsbn.state.la.us/",
    lastVerified: null,
  },
  {
    state: "Maine", stateCode: "ME", slug: "maine", discipline: "rn",
    requirementType: "none", contactHours: null, cycleYears: null,
    summary: "Maine has no mandatory CE requirement for RN license renewal.",
    acceptsNationalAccreditation: true,
    boardName: "Maine State Board of Nursing",
    sourceUrl: "https://www.maine.gov/boardofnursing/",
    lastVerified: null,
  },
  {
    state: "Maryland", stateCode: "MD", slug: "maryland", discipline: "rn",
    requirementType: "none", contactHours: null, cycleYears: null,
    summary: "Maryland has no CE hour mandate for RN renewal; continued competency is attested at renewal.",
    acceptsNationalAccreditation: true,
    boardName: "Maryland Board of Nursing",
    sourceUrl: "https://mbon.maryland.gov/",
    lastVerified: null,
  },
  {
    state: "Massachusetts", stateCode: "MA", slug: "massachusetts", discipline: "rn",
    requirementType: "hours", contactHours: 15, cycleYears: 2,
    summary: "Massachusetts RNs must complete 15 contact hours every 2 years.",
    acceptsNationalAccreditation: true,
    boardName: "Massachusetts Board of Registration in Nursing",
    sourceUrl: "https://www.mass.gov/orgs/board-of-registration-in-nursing",
    lastVerified: null,
  },
  {
    state: "Michigan", stateCode: "MI", slug: "michigan", discipline: "rn",
    requirementType: "hours", contactHours: 25, cycleYears: 2,
    summary: "Michigan RNs must complete 25 contact hours every 2 years, including mandated topics.",
    mandatoryTopics: [
      { topic: "Pain and symptom management", hours: 2, frequency: "every renewal" },
      { topic: "Implicit bias training", hours: 1, frequency: "every renewal (per LARA rules)" },
      { topic: "Human trafficking identification", frequency: "one-time" },
    ],
    acceptsNationalAccreditation: true,
    boardName: "Michigan Board of Nursing (LARA)",
    sourceUrl: "https://www.michigan.gov/lara/bureau-list/bpl/health/hp-lic-health-prof/nursing",
    lastVerified: null,
  },
  {
    state: "Minnesota", stateCode: "MN", slug: "minnesota", discipline: "rn",
    requirementType: "hours", contactHours: 24, cycleYears: 2,
    summary: "Minnesota RNs must complete 24 contact hours every 2 years.",
    acceptsNationalAccreditation: true,
    boardName: "Minnesota Board of Nursing",
    sourceUrl: "https://mn.gov/boards/nursing/",
    lastVerified: null,
  },
  {
    state: "Mississippi", stateCode: "MS", slug: "mississippi", discipline: "rn",
    requirementType: "none", contactHours: null, cycleYears: null,
    summary: "Mississippi has no general CE hour mandate for RN renewal.",
    details: "Verify — Mississippi has considered CE mandates; check current board rules before publishing.",
    acceptsNationalAccreditation: true,
    boardName: "Mississippi Board of Nursing",
    sourceUrl: "https://www.msbn.ms.gov/",
    lastVerified: null,
  },
  {
    state: "Missouri", stateCode: "MO", slug: "missouri", discipline: "rn",
    requirementType: "none", contactHours: null, cycleYears: null,
    summary: "Missouri has no mandatory CE requirement for RN license renewal.",
    acceptsNationalAccreditation: true,
    boardName: "Missouri State Board of Nursing",
    sourceUrl: "https://pr.mo.gov/nursing.asp",
    lastVerified: null,
  },
  {
    state: "Montana", stateCode: "MT", slug: "montana", discipline: "rn",
    requirementType: "hours", contactHours: 24, cycleYears: 2,
    summary: "Montana RNs must complete 24 contact hours every 2 years.",
    acceptsNationalAccreditation: true,
    boardName: "Montana Board of Nursing",
    sourceUrl: "https://boards.bsd.dli.mt.gov/nursing/",
    lastVerified: null,
  },
  {
    state: "Nebraska", stateCode: "NE", slug: "nebraska", discipline: "rn",
    requirementType: "hours", contactHours: 20, cycleYears: 2,
    summary: "Nebraska RNs must complete 20 contact hours every 2 years.",
    acceptsNationalAccreditation: true,
    boardName: "Nebraska Board of Nursing (DHHS)",
    sourceUrl: "https://dhhs.ne.gov/licensure/Pages/Nurse-Licensing.aspx",
    lastVerified: null,
  },
  {
    state: "Nevada", stateCode: "NV", slug: "nevada", discipline: "rn",
    requirementType: "hours", contactHours: 30, cycleYears: 2,
    summary: "Nevada RNs must complete 30 contact hours every 2 years, including mandated topics.",
    mandatoryTopics: [
      { topic: "Bioterrorism / weapons of mass destruction", hours: 4, frequency: "one-time" },
      { topic: "Cultural competency / diversity, equity and inclusion", frequency: "every renewal — verify hours" },
      { topic: "Suicide prevention", frequency: "verify — required for some license types" },
    ],
    acceptsNationalAccreditation: true,
    boardName: "Nevada State Board of Nursing",
    sourceUrl: "https://nevadanursingboard.org/",
    lastVerified: null,
  },
  {
    state: "New Hampshire", stateCode: "NH", slug: "new-hampshire", discipline: "rn",
    requirementType: "hours", contactHours: 30, cycleYears: 2,
    summary: "New Hampshire RNs must complete 30 contact hours every 2 years.",
    acceptsNationalAccreditation: true,
    boardName: "New Hampshire Board of Nursing",
    sourceUrl: "https://www.oplc.nh.gov/board-nursing",
    lastVerified: null,
  },
  {
    state: "New Jersey", stateCode: "NJ", slug: "new-jersey", discipline: "rn",
    requirementType: "hours", contactHours: 30, cycleYears: 2,
    summary: "New Jersey RNs must complete 30 contact hours every 2 years.",
    mandatoryTopics: [
      { topic: "Organ and tissue donation/recovery", hours: 1, frequency: "one-time — verify" },
    ],
    acceptsNationalAccreditation: true,
    boardName: "New Jersey Board of Nursing",
    sourceUrl: "https://www.njconsumeraffairs.gov/nur/",
    lastVerified: null,
  },
  {
    state: "New Mexico", stateCode: "NM", slug: "new-mexico", discipline: "rn",
    requirementType: "hours", contactHours: 30, cycleYears: 2,
    summary: "New Mexico RNs must complete 30 contact hours every 2 years.",
    acceptsNationalAccreditation: true,
    boardName: "New Mexico Board of Nursing",
    sourceUrl: "https://www.bon.nm.gov/",
    lastVerified: null,
  },
  {
    state: "New York", stateCode: "NY", slug: "new-york", discipline: "rn",
    requirementType: "none", contactHours: null, cycleYears: null,
    summary: "New York has no general CE hour mandate for RNs, but requires specific coursework: infection control every 4 years and one-time child abuse identification training.",
    mandatoryTopics: [
      { topic: "Infection control and barrier precautions", frequency: "every 4 years" },
      { topic: "Child abuse identification and reporting", frequency: "one-time" },
    ],
    acceptsNationalAccreditation: true,
    boardName: "New York State Education Department — Office of the Professions",
    sourceUrl: "https://www.op.nysed.gov/professions/registered-professional-nursing",
    lastVerified: null,
  },
  {
    state: "North Carolina", stateCode: "NC", slug: "north-carolina", discipline: "rn",
    requirementType: "options", contactHours: 30, cycleYears: 2,
    summary: "North Carolina RNs must meet one of several continuing-competence options every 2 years — 30 contact hours of CE is a common path, or 15 hours combined with 640 practice hours.",
    acceptsNationalAccreditation: true,
    boardName: "North Carolina Board of Nursing",
    sourceUrl: "https://www.ncbon.com/",
    lastVerified: null,
  },
  {
    state: "North Dakota", stateCode: "ND", slug: "north-dakota", discipline: "rn",
    requirementType: "none", contactHours: null, cycleYears: null,
    summary: "North Dakota has no mandatory CE hour requirement for RN renewal.",
    details: "Verify — ND has practice-hour requirements for renewal; confirm current continued-competency rules.",
    acceptsNationalAccreditation: true,
    boardName: "North Dakota Board of Nursing",
    sourceUrl: "https://www.ndbon.org/",
    lastVerified: null,
  },
  {
    state: "Ohio", stateCode: "OH", slug: "ohio", discipline: "rn",
    requirementType: "hours", contactHours: 24, cycleYears: 2,
    summary: "Ohio RNs must complete 24 contact hours every 2 years, including at least 1 hour of Category A (Ohio law and rules).",
    mandatoryTopics: [
      { topic: "Category A: Ohio nursing law and rules", hours: 1, frequency: "every renewal" },
    ],
    acceptsNationalAccreditation: true,
    boardName: "Ohio Board of Nursing",
    sourceUrl: "https://nursing.ohio.gov/",
    lastVerified: null,
  },
  {
    state: "Oklahoma", stateCode: "OK", slug: "oklahoma", discipline: "rn",
    requirementType: "options", contactHours: 24, cycleYears: 2,
    summary: "Oklahoma RNs must meet one of several competency options every 2 years — 24 contact hours of CE is one qualifying path.",
    details: "Alternatives include national certification and verified practice hours.",
    acceptsNationalAccreditation: true,
    boardName: "Oklahoma Board of Nursing",
    sourceUrl: "https://oklahoma.gov/nursing.html",
    lastVerified: null,
  },
  {
    state: "Oregon", stateCode: "OR", slug: "oregon", discipline: "rn",
    requirementType: "none", contactHours: null, cycleYears: null,
    summary: "Oregon has no recurring CE hour mandate for RNs; a one-time pain management course is required.",
    mandatoryTopics: [
      { topic: "Pain management (Oregon Pain Management Commission module + related coursework)", hours: 7, frequency: "one-time — verify current hours" },
    ],
    acceptsNationalAccreditation: true,
    boardName: "Oregon State Board of Nursing",
    sourceUrl: "https://www.oregon.gov/osbn/",
    lastVerified: null,
  },
  {
    state: "Pennsylvania", stateCode: "PA", slug: "pennsylvania", discipline: "rn",
    requirementType: "hours", contactHours: 30, cycleYears: 2,
    summary: "Pennsylvania RNs must complete 30 contact hours every 2 years, including mandated child abuse recognition training.",
    mandatoryTopics: [
      { topic: "Child abuse recognition and reporting", hours: 2, frequency: "every renewal" },
    ],
    acceptsNationalAccreditation: true,
    boardName: "Pennsylvania State Board of Nursing",
    sourceUrl: "https://www.pa.gov/agencies/dos/department-and-offices/bpoa/boards-commissions/nursing.html",
    lastVerified: null,
  },
  {
    state: "Rhode Island", stateCode: "RI", slug: "rhode-island", discipline: "rn",
    requirementType: "hours", contactHours: 10, cycleYears: 2,
    summary: "Rhode Island RNs must complete 10 contact hours every 2 years.",
    mandatoryTopics: [
      { topic: "Substance abuse", frequency: "verify — historically required within the total" },
    ],
    acceptsNationalAccreditation: true,
    boardName: "Rhode Island Board of Nurse Registration and Nursing Education",
    sourceUrl: "https://health.ri.gov/licenses/detail.php?id=231",
    lastVerified: null,
  },
  {
    state: "South Carolina", stateCode: "SC", slug: "south-carolina", discipline: "rn",
    requirementType: "options", contactHours: 30, cycleYears: 2,
    summary: "South Carolina RNs must meet one of several competency options every 2 years — 30 contact hours of CE is one qualifying path.",
    details: "Alternatives include national certification, academic coursework, or employer-verified practice hours.",
    acceptsNationalAccreditation: true,
    boardName: "South Carolina Board of Nursing (LLR)",
    sourceUrl: "https://llr.sc.gov/nurse/",
    lastVerified: null,
  },
  {
    state: "South Dakota", stateCode: "SD", slug: "south-dakota", discipline: "rn",
    requirementType: "none", contactHours: null, cycleYears: null,
    summary: "South Dakota has no mandatory CE requirement for RN renewal (practice-hour requirements apply instead).",
    acceptsNationalAccreditation: true,
    boardName: "South Dakota Board of Nursing",
    sourceUrl: "https://doh.sd.gov/boards/nursing/",
    lastVerified: null,
  },
  {
    state: "Tennessee", stateCode: "TN", slug: "tennessee", discipline: "rn",
    requirementType: "options", contactHours: null, cycleYears: 2,
    summary: "Tennessee RNs must demonstrate continued competence every 2 years through options that can include continuing education, practice hours, or certification.",
    acceptsNationalAccreditation: true,
    boardName: "Tennessee Board of Nursing",
    sourceUrl: "https://www.tn.gov/health/health-program-areas/health-professional-boards/nursing-board.html",
    lastVerified: null,
  },
  {
    state: "Texas", stateCode: "TX", slug: "texas", discipline: "rn",
    requirementType: "hours", contactHours: 20, cycleYears: 2,
    summary: "Texas RNs must complete 20 contact hours every 2 years (or hold national certification), plus targeted topics for certain practice settings.",
    mandatoryTopics: [
      { topic: "Nursing jurisprudence and ethics", hours: 2, frequency: "every 3rd renewal" },
      { topic: "Human trafficking prevention", frequency: "every renewal" },
      { topic: "Older adult / geriatric care", hours: 2, frequency: "every renewal, if practicing in that population — verify" },
      { topic: "Forensic evidence collection", hours: 2, frequency: "if practicing in an ER — verify" },
    ],
    acceptsNationalAccreditation: true,
    boardName: "Texas Board of Nursing",
    sourceUrl: "https://www.bon.texas.gov/",
    lastVerified: null,
  },
  {
    state: "Utah", stateCode: "UT", slug: "utah", discipline: "rn",
    requirementType: "options", contactHours: 30, cycleYears: 2,
    summary: "Utah RNs must meet continued-competency requirements every 2 years — CE hours scale with practice hours (e.g. 30 CE hours if practicing fewer than 200 hours; 15 CE hours with 200–399 practice hours; none with 400+).",
    details: "Verify the current practice-hour tiers.",
    acceptsNationalAccreditation: true,
    boardName: "Utah Division of Professional Licensing — Board of Nursing",
    sourceUrl: "https://dopl.utah.gov/nurse/",
    lastVerified: null,
  },
  {
    state: "Vermont", stateCode: "VT", slug: "vermont", discipline: "rn",
    requirementType: "none", contactHours: null, cycleYears: null,
    summary: "Vermont has no CE hour mandate for RN renewal (practice-hour requirements apply instead).",
    acceptsNationalAccreditation: true,
    boardName: "Vermont Board of Nursing",
    sourceUrl: "https://sos.vermont.gov/nursing/",
    lastVerified: null,
  },
  {
    state: "Virginia", stateCode: "VA", slug: "virginia", discipline: "rn",
    requirementType: "options", contactHours: 30, cycleYears: 2,
    summary: "Virginia RNs must meet one of several continued-competency options every 2 years — 30 contact hours of CE is one path; 15 hours plus 640 practice hours is another.",
    acceptsNationalAccreditation: true,
    boardName: "Virginia Board of Nursing",
    sourceUrl: "https://www.dhp.virginia.gov/nursing/",
    lastVerified: null,
  },
  {
    state: "Washington", stateCode: "WA", slug: "washington", discipline: "rn",
    requirementType: "hours", contactHours: 45, cycleYears: 3,
    summary: "Washington RNs must complete 45 contact hours every 3 years plus 531 active practice hours, with additional one-time and recurring topic mandates.",
    mandatoryTopics: [
      { topic: "Suicide prevention", hours: 6, frequency: "one-time" },
      { topic: "Health equity", hours: 2, frequency: "every 4 years — verify" },
    ],
    acceptsNationalAccreditation: true,
    boardName: "Washington State Nursing Care Quality Assurance Commission",
    sourceUrl: "https://nursing.wa.gov/",
    lastVerified: null,
  },
  {
    state: "West Virginia", stateCode: "WV", slug: "west-virginia", discipline: "rn",
    requirementType: "hours", contactHours: 12, cycleYears: 1,
    summary: "West Virginia RNs must complete 12 contact hours each annual reporting period, with periodic mandated topics.",
    mandatoryTopics: [
      { topic: "Substance use disorder / drug diversion", frequency: "verify — periodic mandate" },
      { topic: "Mental health conditions common to veterans", hours: 2, frequency: "one-time — verify" },
    ],
    acceptsNationalAccreditation: true,
    boardName: "West Virginia RN Board",
    sourceUrl: "https://wvrnboard.wv.gov/",
    lastVerified: null,
  },
  {
    state: "Wisconsin", stateCode: "WI", slug: "wisconsin", discipline: "rn",
    requirementType: "none", contactHours: null, cycleYears: null,
    summary: "Wisconsin has no mandatory CE requirement for RN license renewal.",
    acceptsNationalAccreditation: true,
    boardName: "Wisconsin Board of Nursing",
    sourceUrl: "https://dsps.wi.gov/Pages/BoardsCouncils/Nursing/",
    lastVerified: null,
  },
  {
    state: "Wyoming", stateCode: "WY", slug: "wyoming", discipline: "rn",
    requirementType: "options", contactHours: 20, cycleYears: 2,
    summary: "Wyoming RNs must meet continued-competency options every 2 years — contact hours combined with practice hours is a common path.",
    details: "Verify the current option tiers (CE hours vs. practice hours vs. certification).",
    acceptsNationalAccreditation: true,
    boardName: "Wyoming State Board of Nursing",
    sourceUrl: "https://nursing-online.state.wy.us/",
    lastVerified: null,
  },
  {
    state: "Washington, D.C.", stateCode: "DC", slug: "washington-dc", discipline: "rn",
    requirementType: "hours", contactHours: 24, cycleYears: 2,
    summary: "D.C. RNs must complete 24 contact hours every 2 years, including district-mandated topics.",
    mandatoryTopics: [
      { topic: "LGBTQ cultural competency", hours: 2, frequency: "every renewal" },
      { topic: "Public health priorities (per DOH)", frequency: "every renewal — verify current topics" },
    ],
    acceptsNationalAccreditation: true,
    boardName: "District of Columbia Board of Nursing",
    sourceUrl: "https://dchealth.dc.gov/bon",
    lastVerified: null,
  },
];
