// lib/ce-requirements/sw-data.ts
// Social worker continuing education requirements — 48 states + DC.
// CA and NY are intentionally EXCLUDED (same policy as rn-data.ts): both require
// state-specific provider approval that national accreditation alone may not satisfy.
//
// ⚠️ Entries with lastVerified: null are PRE-FILLED and UNVERIFIED — they never
// render publicly. Verify against the board site, correct, set lastVerified, push.
// The 10 entries verified 2026-07-30 were researched against official board/statute
// pages (citations in the 2026-07-30 session + project changelog).
//
// Social work nuance: most states license multiple levels (LBSW/LMSW/LCSW etc.).
// Main fields hold the general rule; level differences live in `details`.
// acceptsNationalAccreditation here means "accepts ASWB ACE-approved provider CE".

import type { StateRequirement } from "./types";

export const SW_REQUIREMENTS: StateRequirement[] = [
  {
    state: "Alabama", stateCode: "AL", slug: "alabama", discipline: "social-work",
    requirementType: "hours", contactHours: 30, cycleYears: 2,
    summary: "Alabama social workers must complete 30 hours of continuing education every 2 years.",
    details: "Verify hour split by level (LBSW/LMSW/LICSW) and any ethics minimum.",
    acceptsNationalAccreditation: true,
    boardName: "Alabama State Board of Social Work Examiners",
    sourceUrl: "https://socialwork.alabama.gov/",
    lastVerified: null,
  },
  {
    state: "Alaska", stateCode: "AK", slug: "alaska", discipline: "social-work",
    requirementType: "hours", contactHours: 45, cycleYears: 2,
    summary: "Alaska social workers must complete 45 contact hours every 2 years, including ethics coursework.",
    details: "Verify current hours, ethics minimum, and any substance-abuse/cross-cultural mandates.",
    acceptsNationalAccreditation: true,
    boardName: "Alaska Board of Social Work Examiners",
    sourceUrl: "https://www.commerce.alaska.gov/web/cbpl/professionallicensing/boardofsocialworkexaminers.aspx",
    lastVerified: null,
  },
  {
    state: "Arizona", stateCode: "AZ", slug: "arizona", discipline: "social-work",
    requirementType: "hours", contactHours: 30, cycleYears: 2,
    summary: "Arizona social workers (LBSW, LMSW, and LCSW) must complete 30 clock hours of continuing education every 2-year license period.",
    details: "Excess hours cannot be carried over to the next license period. Renewal runs through the Board's online portal, which includes a CEU Tracker you can log hours in as you go — the renewal application opens 90 days before your expiration date. In addition to coursework, Arizona requires completion of the Board's own Arizona Statutes/Regulations Tutorial each license period.",
    mandatoryTopics: [
      { topic: "Behavioral health ethics or mental health law", hours: 3, frequency: "every renewal" },
      { topic: "Cultural competency and diversity", hours: 3, frequency: "every renewal" },
      { topic: "Arizona Statutes/Regulations Tutorial (delivered by the Board)", frequency: "every renewal" },
    ],
    acceptsNationalAccreditation: true,
    accreditationNote: "Arizona accepts CE sponsored or approved by national, regional, or state professional associations in social work and allied professions, which includes ASWB ACE-approved providers. The Arizona Statutes/Regulations Tutorial is the one exception — it comes from the Board itself and can't be replaced by outside coursework.",
    boardName: "Arizona Board of Behavioral Health Examiners",
    sourceUrl: "https://bbhe.az.gov/license-renewal",
    lastVerified: "2026-08-14",
  },
  {
    state: "Arkansas", stateCode: "AR", slug: "arkansas", discipline: "social-work",
    requirementType: "hours", contactHours: 30, cycleYears: 2,
    summary: "Arkansas social workers must complete 30 hours of continuing education every 2 years, including ethics.",
    details: "Verify ethics minimum and level differences (LSW/LMSW/LCSW).",
    acceptsNationalAccreditation: true,
    boardName: "Arkansas Social Work Licensing Board",
    sourceUrl: "https://www.arkansas.gov/swlb/",
    lastVerified: null,
  },
  {
    state: "Colorado", stateCode: "CO", slug: "colorado", discipline: "social-work",
    requirementType: "hours", contactHours: 40, cycleYears: 2,
    summary: "Colorado LCSWs must complete 40 professional development hours every 2 years.",
    details: "Verify the current Continuing Professional Development (CPD) program requirements and jurisprudence coursework.",
    acceptsNationalAccreditation: true,
    boardName: "Colorado State Board of Social Work Examiners (DORA)",
    sourceUrl: "https://dpo.colorado.gov/SocialWork",
    lastVerified: null,
  },
  {
    state: "Connecticut", stateCode: "CT", slug: "connecticut", discipline: "social-work",
    requirementType: "hours", contactHours: 15, cycleYears: 1,
    summary: "Connecticut social workers must complete 15 hours of continuing education each year, including cultural competency and veterans' mental health coursework.",
    details: "Verify current annual hours and the cultural competency / mental health of veterans mandates.",
    mandatoryTopics: [
      { topic: "Cultural competency", frequency: "periodic — verify current rule" },
      { topic: "Mental health conditions common to veterans", frequency: "periodic — verify current rule" },
    ],
    acceptsNationalAccreditation: true,
    boardName: "Connecticut Department of Public Health",
    sourceUrl: "https://portal.ct.gov/dph",
    lastVerified: null,
  },
  {
    state: "Delaware", stateCode: "DE", slug: "delaware", discipline: "social-work",
    requirementType: "hours", contactHours: 45, cycleYears: 2,
    summary: "Delaware clinical social workers must complete 45 hours of continuing education every 2 years.",
    details: "Verify hours by level and any ethics/suicide-prevention mandates.",
    acceptsNationalAccreditation: true,
    boardName: "Delaware Board of Clinical Social Work Examiners",
    sourceUrl: "https://dpr.delaware.gov/boards/socialworkers/",
    lastVerified: null,
  },
  {
    state: "Florida", stateCode: "FL", slug: "florida", discipline: "social-work",
    requirementType: "hours", contactHours: 30, cycleYears: 2,
    summary: "Florida licensed clinical social workers must complete 30 hours of approved continuing education each biennium, including medical errors and ethics-or-telehealth coursework, with laws-and-rules and domestic violence courses due every third renewal.",
    mandatoryTopics: [
      { topic: "Prevention of medical errors", hours: 2, frequency: "every renewal; counts within the 30" },
      { topic: "Professional ethics and boundary issues OR telehealth", hours: 3, frequency: "every renewal (same course may not repeat in consecutive periods); counts within the 30" },
      { topic: "Florida laws and rules (board-approved provider)", hours: 3, frequency: "every 3rd renewal; counts within the 30" },
      { topic: "Domestic violence", hours: 2, frequency: "within 6 months of initial licensure and every 3rd renewal; counts within the 30" },
    ],
    details: "Rule 64B4-6.001 F.A.C. No CE is required for the first renewal. A maximum of 6 of the 30 hours may be non-clinical/administrative. One-time licensure (not renewal) requirements: 8-hour laws and rules course, 3-hour HIV/AIDS course, and the domestic violence course within 6 months. The 1-hour human trafficking CE in s. 456.0341 does NOT apply to chapter 491 licensees. All CE is tracked in CE Broker and reviewed at renewal. Approved sources include Board-approved providers and national entities listed in Rule 64B4-6.002 (ASWB, NASW, APA, NBCC, and others). Licenses expire March 31 of odd years. The same rule covers the board's LMFT and LMHC licensees.",
    acceptsNationalAccreditation: true,
    boardName: "Florida Board of Clinical Social Work, Marriage & Family Therapy and Mental Health Counseling",
    sourceUrl: "https://www.flrules.org/gateway/ruleno.asp?id=64B4-6.001",
    lastVerified: "2026-07-30",
  },
  {
    state: "Georgia", stateCode: "GA", slug: "georgia", discipline: "social-work",
    requirementType: "hours", contactHours: 35, cycleYears: 2,
    summary: "Georgia social workers must complete 35 hours of continuing education each 2-year renewal cycle ending September 30 of even-numbered years, including 5 hours of professional ethics.",
    mandatoryTopics: [
      { topic: "Professional ethics (synchronous activities only)", hours: 5, frequency: "every renewal; counts within the 35" },
    ],
    details: "Composite Board Rule 135-9-.01; applies to LMSW and LCSW. The biennial cycle runs October 1 (even year) through September 30 (next even year). Of the remaining 30 hours, at least 15 must be 'core' hours in social work; up to 15 may be 'related' hours. Caps: max 10 hours asynchronous per cycle, independent study limited to 5 hours, graduate coursework capped at 20. Acceptable CE comes from professional associations in the specialty (e.g. NASW), accredited academic departments, or licensing boards in other jurisdictions — ASWB ACE-approved CE is recognized. No first-renewal CE if licensed during the second year of the cycle. Attestation at renewal; keep documentation for audit.",
    acceptsNationalAccreditation: true,
    boardName: "Georgia Composite Board of Professional Counselors, Social Workers and Marriage and Family Therapists",
    sourceUrl: "https://rules.sos.ga.gov/gac/135-9-.01",
    lastVerified: "2026-07-30",
  },
  {
    state: "Hawaii", stateCode: "HI", slug: "hawaii", discipline: "social-work",
    requirementType: "hours", contactHours: 45, cycleYears: 3,
    summary: "Hawaii social workers must complete continuing education each 3-year renewal period — verify the current hour requirement.",
    details: "Verify current hours, cycle, and provider rules.",
    acceptsNationalAccreditation: true,
    boardName: "Hawaii Board of Social Work",
    sourceUrl: "https://cca.hawaii.gov/pvl/programs/socialworker/",
    lastVerified: null,
  },
  {
    state: "Idaho", stateCode: "ID", slug: "idaho", discipline: "social-work",
    requirementType: "hours", contactHours: 20, cycleYears: 1,
    summary: "Idaho social workers must complete 20 hours of continuing education each year, including ethics coursework.",
    details: "Verify current annual hours and ethics minimum.",
    acceptsNationalAccreditation: true,
    boardName: "Idaho Board of Social Work Examiners",
    sourceUrl: "https://dopl.idaho.gov/bsw/",
    lastVerified: null,
  },
  {
    state: "Illinois", stateCode: "IL", slug: "illinois", discipline: "social-work",
    requirementType: "hours", contactHours: 30, cycleYears: 2,
    summary: "Illinois LSWs and LCSWs must complete 30 hours of continuing education every 2 years, including 3 hours of ethics, 3 hours of cultural competence, and one-hour state mandates in sexual harassment prevention and implicit bias awareness.",
    mandatoryTopics: [
      { topic: "Social work practice ethics", hours: 3, frequency: "every renewal; counts within the 30" },
      { topic: "Cultural competence", hours: 3, frequency: "every renewal; counts within the 30" },
      { topic: "Sexual harassment prevention", hours: 1, frequency: "every renewal; counts within the 30" },
      { topic: "Implicit bias awareness", hours: 1, frequency: "every renewal; counts within the 30" },
      { topic: "Alzheimer's disease and other dementias", hours: 1, frequency: "once every 6 years, for licensees serving adults 26+; counts within the 30" },
      { topic: "Clinical supervision training (LCSW only)", hours: 6, frequency: "one-time, beginning with the renewal ending Nov 30, 2027; counts within the 30" },
    ],
    details: "68 Ill. Adm. Code 1470.95; applies to LSW and LCSW. Licenses renew by November 30 of odd-numbered years. No CE for the first renewal. Social work's profession-specific 3-hour cultural competence rule exceeds IDFPR's generic 1-hour mandate. Mandated reporter training (DCFS) is a separate obligation (within 3 months of engagement, then at least every 3 years) but counts toward CE hours. Accepted sponsors include IDFPR-licensed CE sponsors, ASWB (ACE), NASW and affiliates, and accredited universities.",
    acceptsNationalAccreditation: true,
    boardName: "Illinois Department of Financial and Professional Regulation (Division of Professional Regulation)",
    sourceUrl: "https://idfpr.illinois.gov/content/dam/soi/en/web/idfpr/forms/dpr/ce-sw.pdf",
    lastVerified: "2026-07-30",
  },
  {
    state: "Indiana", stateCode: "IN", slug: "indiana", discipline: "social-work",
    requirementType: "hours", contactHours: 40, cycleYears: 2,
    summary: "Indiana social workers must complete 40 hours of continuing education every 2 years, including ethics.",
    details: "Verify current hours, ethics category minimum, and level differences (LBSW/LSW/LCSW).",
    acceptsNationalAccreditation: true,
    boardName: "Indiana Behavioral Health and Human Services Licensing Board",
    sourceUrl: "https://www.in.gov/pla/professions/behavioral-health-home/",
    lastVerified: null,
  },
  {
    state: "Iowa", stateCode: "IA", slug: "iowa", discipline: "social-work",
    requirementType: "hours", contactHours: 27, cycleYears: 2,
    summary: "Iowa social workers must complete 27 hours of continuing education every 2 years, including ethics.",
    mandatoryTopics: [
      { topic: "Social work ethics", hours: 3, frequency: "every renewal — verify" },
      { topic: "Dependent adult abuse / child abuse identification", hours: 2, frequency: "every 5 years, if serving those populations — verify" },
    ],
    acceptsNationalAccreditation: true,
    boardName: "Iowa Board of Social Work",
    sourceUrl: "https://idph.iowa.gov/licensure/iowa-board-of-social-work",
    lastVerified: null,
  },
  {
    state: "Kansas", stateCode: "KS", slug: "kansas", discipline: "social-work",
    requirementType: "hours", contactHours: 40, cycleYears: 2,
    summary: "Kansas social workers must complete 40 hours of continuing education every 2 years, including 3 hours of professional ethics.",
    mandatoryTopics: [
      { topic: "Professional ethics", hours: 3, frequency: "every renewal; counts within the 40" },
      { topic: "Diagnosis and treatment of mental disorders (LMSW and LSCSW only)", hours: 3, frequency: "every renewal; counts within the 40 (reduced from 6 hours effective July 1, 2025)" },
      { topic: "Social work safety awareness training", hours: 6, frequency: "one-time, at first renewal of any license level; counts within the 40" },
    ],
    details: "Applies to LBSW, LMSW, LSCSW, and LASW. BSRB provider pre-approval is optional — CE must be 'oriented to the enhancement of social work practice, values, ethics, skills or knowledge,' so ASWB ACE-approved provider CE is generally accepted (verified at audit). Under K.A.R. 102-2-4a, self-directed study without a posttest is capped at 10 hours per cycle; excess hours do not carry over.",
    acceptsNationalAccreditation: true,
    boardName: "Kansas Behavioral Sciences Regulatory Board",
    sourceUrl: "https://www.ksbsrb.ks.gov/professions/social-workers/faqs",
    lastVerified: "2026-07-30",
  },
  {
    state: "Kentucky", stateCode: "KY", slug: "kentucky", discipline: "social-work",
    requirementType: "hours", contactHours: 30, cycleYears: 3,
    summary: "Kentucky social workers must complete continuing education each 3-year renewal cycle, including ethics — verify the current hour requirement.",
    details: "Verify hours per cycle, ethics minimum, and any suicide-prevention mandate.",
    acceptsNationalAccreditation: true,
    boardName: "Kentucky Board of Social Work",
    sourceUrl: "https://bsw.ky.gov/",
    lastVerified: null,
  },
  {
    state: "Louisiana", stateCode: "LA", slug: "louisiana", discipline: "social-work",
    requirementType: "hours", contactHours: 20, cycleYears: 1,
    summary: "Louisiana social workers must complete 20 hours of continuing education each year, including 3 hours of social work ethics every two years.",
    mandatoryTopics: [
      { topic: "Social work ethics", hours: 3, frequency: "every 2 years; counts within the annual 20" },
      { topic: "Clinical content including diagnosis and treatment (LCSW only)", hours: 10, frequency: "annually; counts within the annual 20" },
      { topic: "Clinical supervision (LCSW-BACS only)", hours: 3, frequency: "every 2 years" },
    ],
    details: "Renewal is annual; the CE reporting period runs September 1 through August 31. Applies to all credential levels (RSW, LMSW, CSW, LCSW). Distance learning is capped at 10 of the 20 annual hours. Acceptable CE includes programs from social work licensing bodies, state and national professional social work organizations, CSWE-accredited schools, and ASWB-approved entities. First-year requirements are prorated by month of initial credentialing.",
    acceptsNationalAccreditation: true,
    boardName: "Louisiana State Board of Social Work Examiners",
    sourceUrl: "https://www.labswe.org/continuing-education/",
    lastVerified: "2026-07-30",
  },
  {
    state: "Maine", stateCode: "ME", slug: "maine", discipline: "social-work",
    requirementType: "hours", contactHours: 25, cycleYears: 2,
    summary: "Maine social workers must complete 25 hours of continuing education every 2 years, including 4 hours of ethics.",
    details: "Verify current hours and ethics minimum.",
    acceptsNationalAccreditation: true,
    boardName: "Maine State Board of Social Worker Licensure",
    sourceUrl: "https://www.maine.gov/pfr/professionallicensing/professions/social-workers",
    lastVerified: null,
  },
  {
    state: "Maryland", stateCode: "MD", slug: "maryland", discipline: "social-work",
    requirementType: "hours", contactHours: 40, cycleYears: 2,
    summary: "Maryland social workers must complete 40 credit hours every 2 years, including 3 hours of ethics.",
    details: "Verify Category I minimums and the implicit bias / cultural competency mandates.",
    mandatoryTopics: [
      { topic: "Ethics and professional conduct", hours: 3, frequency: "every renewal — verify" },
      { topic: "Implicit bias / structural racism", frequency: "verify — Maryland enacted a health-professional mandate" },
    ],
    acceptsNationalAccreditation: true,
    boardName: "Maryland Board of Social Work Examiners",
    sourceUrl: "https://health.maryland.gov/bswe/",
    lastVerified: null,
  },
  {
    state: "Massachusetts", stateCode: "MA", slug: "massachusetts", discipline: "social-work",
    requirementType: "hours", contactHours: 30, cycleYears: 2,
    contactHoursByLevel: "30 (LICSW) · 20 (LCSW) · 15 (LSW) · 10 (LSWA)",
    summary: "Massachusetts requires CE tiered by license level every 2 years: 30 hours for LICSWs, 20 for LCSWs, 15 for LSWs, and 10 for LSWAs.",
    details: "All hours may be completed through distance learning. Social workers who practice exclusively as employees of Massachusetts state, county, or municipal government are exempt from the CE requirement. Massachusetts also requires a Board-approved domestic and sexual violence training — confirm its current frequency with the Board. A continuing education hour is at least 50 minutes of instruction.",
    mandatoryTopics: [
      { topic: "Anti-racism (with a focus on oppression)", hours: 2, frequency: "every renewal" },
      { topic: "Anti-discrimination", hours: 1, frequency: "every renewal" },
    ],
    acceptsNationalAccreditation: true,
    accreditationNote: "Massachusetts requires at least 75% of your hours to come from Board-recognized entities (258 CMR 31.04(2)); up to 25% may come from programs approved by the APA, NBCC, ANCC, or ACCME. ASWB ACE-approved provider courses are accepted under Board practice.",
    boardName: "Massachusetts Board of Registration of Social Workers",
    sourceUrl: "https://www.mass.gov/regulations/258-CMR-3100-continuing-education-requirements",
    lastVerified: "2026-08-14",
  },
  {
    state: "Michigan", stateCode: "MI", slug: "michigan", discipline: "social-work",
    requirementType: "hours", contactHours: 45, cycleYears: 3,
    summary: "Michigan social workers must complete 45 hours of continuing education every 3 years, including 5 hours of ethics, 2 hours of pain and symptom management, 2 hours of human trafficking, and 1 hour of implicit bias training per year of the cycle.",
    mandatoryTopics: [
      { topic: "Ethics", hours: 5, frequency: "every renewal; counts within the 45" },
      { topic: "Pain and pain symptom management", hours: 2, frequency: "every renewal; counts within the 45" },
      { topic: "Human trafficking", hours: 2, frequency: "every renewal; counts within the 45 (plus one-time training before initial licensure)" },
      { topic: "Implicit bias", hours: 3, frequency: "every renewal (1 hour per year of the 3-year cycle); may count within the 45" },
    ],
    details: "R 338.2961–2963; applies to fully licensed LBSWs and LMSWs. At least half of the 45 hours must be completed in person or in a live synchronous format. Acceptable CE includes programs approved by ASWB, NASW (national or state chapters), the Michigan board, or other states' social work boards. Keep CE documentation 5 years (6 for implicit bias).",
    acceptsNationalAccreditation: true,
    boardName: "Michigan Board of Social Work (LARA Bureau of Professional Licensing)",
    sourceUrl: "https://www.michigan.gov/lara/bureau-list/bpl/health/hp-lic-health-prof/social",
    lastVerified: "2026-07-30",
  },
  {
    state: "Minnesota", stateCode: "MN", slug: "minnesota", discipline: "social-work",
    requirementType: "hours", contactHours: 40, cycleYears: 2,
    summary: "Minnesota social workers must complete 40 hours of continuing education every 2 years, including ethics.",
    details: "Verify ethics minimum (2 hrs?) and clinical-hour rules for LICSWs.",
    acceptsNationalAccreditation: true,
    boardName: "Minnesota Board of Social Work",
    sourceUrl: "https://mn.gov/boards/social-work/",
    lastVerified: null,
  },
  {
    state: "Mississippi", stateCode: "MS", slug: "mississippi", discipline: "social-work",
    requirementType: "hours", contactHours: 40, cycleYears: 2,
    summary: "Mississippi social workers must complete 40 hours of continuing education every 2 years, including ethics.",
    details: "Verify current hours, ethics minimum, and any cultural-competency mandate.",
    acceptsNationalAccreditation: true,
    boardName: "Mississippi Board of Examiners for Social Workers and Marriage & Family Therapists",
    sourceUrl: "https://www.swmft.ms.gov/",
    lastVerified: null,
  },
  {
    state: "Missouri", stateCode: "MO", slug: "missouri", discipline: "social-work",
    requirementType: "hours", contactHours: 30, cycleYears: 2,
    summary: "Missouri social workers must complete 30 hours of continuing education every 2 years, including 3 hours of ethics.",
    details: "Verify current hours and ethics minimum by level.",
    acceptsNationalAccreditation: true,
    boardName: "Missouri State Committee for Social Workers",
    sourceUrl: "https://pr.mo.gov/socialworkers.asp",
    lastVerified: null,
  },
  {
    state: "Montana", stateCode: "MT", slug: "montana", discipline: "social-work",
    requirementType: "hours", contactHours: 20, cycleYears: 1,
    summary: "Montana social workers must complete 20 hours of continuing education each year.",
    details: "Verify current annual hours and any ethics/suicide-prevention mandates.",
    acceptsNationalAccreditation: true,
    boardName: "Montana Board of Behavioral Health",
    sourceUrl: "https://boards.bsd.dli.mt.gov/behavioral-health/",
    lastVerified: null,
  },
  {
    state: "Nebraska", stateCode: "NE", slug: "nebraska", discipline: "social-work",
    requirementType: "hours", contactHours: 32, cycleYears: 2,
    summary: "Nebraska social workers must complete 32 hours of continuing education every 2 years.",
    details: "Verify current hours and any ethics minimum.",
    acceptsNationalAccreditation: true,
    boardName: "Nebraska DHHS — Board of Mental Health Practice",
    sourceUrl: "https://dhhs.ne.gov/licensure/Pages/Mental-Health-and-Social-Work-Practice.aspx",
    lastVerified: null,
  },
  {
    state: "Nevada", stateCode: "NV", slug: "nevada", discipline: "social-work",
    requirementType: "hours", contactHours: 30, cycleYears: 1,
    summary: "Nevada social workers must complete continuing education each annual renewal — verify the current hour requirement.",
    details: "Verify annual hours, ethics minimum, and any suicide-prevention/cultural-competency mandates.",
    acceptsNationalAccreditation: true,
    boardName: "Nevada Board of Examiners for Social Workers",
    sourceUrl: "https://socwork.nv.gov/",
    lastVerified: null,
  },
  {
    state: "New Hampshire", stateCode: "NH", slug: "new-hampshire", discipline: "social-work",
    requirementType: "hours", contactHours: 40, cycleYears: 2,
    summary: "New Hampshire clinical social workers must complete 40 hours of continuing education every 2 years, including ethics and suicide-prevention coursework.",
    details: "Verify current hours, ethics minimum, and the suicide prevention mandate (3 hrs every renewal?).",
    acceptsNationalAccreditation: true,
    boardName: "New Hampshire Board of Mental Health Practice",
    sourceUrl: "https://www.oplc.nh.gov/board-mental-health-practice",
    lastVerified: null,
  },
  {
    state: "New Jersey", stateCode: "NJ", slug: "new-jersey", discipline: "social-work",
    requirementType: "hours", contactHours: 40, cycleYears: 2,
    summary: "New Jersey social workers must complete 40 credits of continuing education every 2 years, including 5 in ethics.",
    details: "Verify: LCSWs need 20 clinical credits within the 40; social and cultural competence credits required. LSW/LCSW/CSW levels differ.",
    mandatoryTopics: [
      { topic: "Ethics", hours: 5, frequency: "every renewal — verify" },
      { topic: "Social and cultural competence", frequency: "verify current rule" },
    ],
    acceptsNationalAccreditation: true,
    boardName: "New Jersey State Board of Social Work Examiners",
    sourceUrl: "https://www.njconsumeraffairs.gov/sw/",
    lastVerified: null,
  },
  {
    state: "New Mexico", stateCode: "NM", slug: "new-mexico", discipline: "social-work",
    requirementType: "hours", contactHours: 30, cycleYears: 2,
    summary: "New Mexico social workers must complete 30 hours of continuing education every 2 years, including cultural awareness coursework.",
    details: "Verify the cultural-awareness (6 hrs?) and ethics minimums.",
    acceptsNationalAccreditation: true,
    boardName: "New Mexico Board of Social Work Examiners",
    sourceUrl: "https://www.rld.nm.gov/boards-and-commissions/individual-boards-and-commissions/social-work-examiners/",
    lastVerified: null,
  },
  {
    state: "North Carolina", stateCode: "NC", slug: "north-carolina", discipline: "social-work",
    requirementType: "hours", contactHours: 40, cycleYears: 2,
    summary: "North Carolina social workers must complete 40 contact hours of continuing education every 2-year renewal cycle, including at least 4 hours of ethics.",
    mandatoryTopics: [
      { topic: "Ethics", hours: 4, frequency: "every renewal; counts within the 40 (prorated for shorter cycles)" },
    ],
    details: "Applies to all credential levels (CSW, CMSW, LCSW, LCSWA). The renewal cycle runs from date of issue or last renewal (rolling, not calendar-fixed); requirements prorate for shorter periods (20 hrs + 2 ethics per year). A maximum of 20 of the 40 hours may be distance learning, and distance courses must be pre-approved by ASWB ACE or NASW-NC. The board does not pre-approve live courses or providers (audit-based) — keep documentation.",
    acceptsNationalAccreditation: true,
    boardName: "North Carolina Social Work Certification and Licensure Board",
    sourceUrl: "https://www.ncswboard.gov/continuing-education-information/",
    lastVerified: "2026-07-30",
  },
  {
    state: "North Dakota", stateCode: "ND", slug: "north-dakota", discipline: "social-work",
    requirementType: "hours", contactHours: 30, cycleYears: 2,
    summary: "North Dakota social workers must complete 30 hours of continuing education every 2 years.",
    details: "Verify current hours and any ethics minimum.",
    acceptsNationalAccreditation: true,
    boardName: "North Dakota Board of Social Work Examiners",
    sourceUrl: "https://www.ndbswe.com/",
    lastVerified: null,
  },
  {
    state: "Ohio", stateCode: "OH", slug: "ohio", discipline: "social-work",
    requirementType: "hours", contactHours: 30, cycleYears: 2,
    summary: "Ohio social workers (LSW and LISW) must complete 30 hours of continuing education every 2 years, including 3 hours in ethics.",
    mandatoryTopics: [
      { topic: "Ethics", hours: 3, frequency: "every renewal; counts within the 30" },
      { topic: "Supervision (LISW-S designation only)", hours: 3, frequency: "every renewal; counts within the 30" },
    ],
    details: "OAC 4757-9-01. All CE must be completed and reported through CE Broker before renewal. The board automatically accepts CE approved by the CSWMFT Board, ASWB ACE, national NASW, or NASW-Ohio. Up to 12 hours may carry over to the next renewal period. Renewal runs on each licensee's individual 2-year cycle; CE is not required for Inactive/Escrow status.",
    acceptsNationalAccreditation: true,
    boardName: "Ohio Counselor, Social Worker and Marriage & Family Therapist (CSWMFT) Board",
    sourceUrl: "https://cswmft.ohio.gov/license-renewal/renewal-resources/before-you-renew",
    lastVerified: "2026-07-30",
  },
  {
    state: "Oklahoma", stateCode: "OK", slug: "oklahoma", discipline: "social-work",
    requirementType: "hours", contactHours: 16, cycleYears: 1,
    summary: "Oklahoma social workers must complete 16 hours of continuing education each year, including ethics.",
    details: "Verify annual hours (16?) and the ethics minimum.",
    acceptsNationalAccreditation: true,
    boardName: "Oklahoma State Board of Licensed Social Workers",
    sourceUrl: "https://www.ok.gov/socialworkers/",
    lastVerified: null,
  },
  {
    state: "Oregon", stateCode: "OR", slug: "oregon", discipline: "social-work",
    requirementType: "hours", contactHours: 40, cycleYears: 2,
    summary: "Oregon social workers must complete 40 hours of continuing education every 2 years, including ethics and (one-time) suicide-risk training.",
    details: "Verify ethics hours (6?), the one-time suicide risk assessment/treatment training for clinical licensees, and cultural-competency rules.",
    mandatoryTopics: [
      { topic: "Ethics", hours: 6, frequency: "every renewal — verify" },
      { topic: "Suicide risk assessment, treatment and management (LCSWs)", frequency: "one-time — verify hours" },
    ],
    acceptsNationalAccreditation: true,
    boardName: "Oregon Board of Licensed Social Workers",
    sourceUrl: "https://www.oregon.gov/blsw/",
    lastVerified: null,
  },
  {
    state: "Pennsylvania", stateCode: "PA", slug: "pennsylvania", discipline: "social-work",
    requirementType: "hours", contactHours: 30, cycleYears: 2,
    summary: "Pennsylvania social workers must complete 30 hours of continuing education every 2 years, including 3 hours of ethics, 2 hours of child abuse recognition and reporting, and 1 hour of suicide prevention.",
    mandatoryTopics: [
      { topic: "Professional ethics", hours: 3, frequency: "every renewal; counts within the 30" },
      { topic: "Child abuse recognition and reporting (Act 31, approved provider)", hours: 2, frequency: "every renewal; counts within the 30 (3 hours at initial licensure)" },
      { topic: "Suicide risk assessment, treatment and management (Act 74)", hours: 1, frequency: "every renewal; counts within the 30 but may NOT count toward the ethics hours" },
    ],
    details: "Applies to LBSW, LSW, and LCSW; licenses expire end of February in odd-numbered years. New licensees are exempt from the 30 hours for their first biennium except the 2-hour child abuse training. No live/in-person CE requirement. Preapproved providers under 49 Pa. Code 47.36 include ASWB ACE-approved providers, ASWB itself, NASW and affiliates, CSWE-accredited programs, and accredited universities. The 2026 organ-donation CE mandate applies to medical/nursing licensees, not social workers.",
    acceptsNationalAccreditation: true,
    boardName: "Pennsylvania State Board of Social Workers, Marriage and Family Therapists and Professional Counselors",
    sourceUrl: "https://www.pa.gov/agencies/dos/department-and-offices/bpoa/boards-commissions/social-workers-marriage-family-therapists-professional-counselors/renewal-information",
    lastVerified: "2026-07-30",
  },
  {
    state: "Rhode Island", stateCode: "RI", slug: "rhode-island", discipline: "social-work",
    requirementType: "hours", contactHours: 30, cycleYears: 2,
    summary: "Rhode Island social workers must complete 30 hours of continuing education every 2 years, including ethics.",
    details: "Verify current hours and any cross-cultural mandate.",
    acceptsNationalAccreditation: true,
    boardName: "Rhode Island Department of Health — Board of Social Work Examiners",
    sourceUrl: "https://health.ri.gov/licenses/detail.php?id=252",
    lastVerified: null,
  },
  {
    state: "South Carolina", stateCode: "SC", slug: "south-carolina", discipline: "social-work",
    requirementType: "hours", contactHours: 40, cycleYears: 2,
    summary: "South Carolina social workers must complete 40 hours of continuing education every 2 years, including ethics.",
    details: "Verify current hours and ethics minimum by level.",
    acceptsNationalAccreditation: true,
    boardName: "South Carolina Board of Social Work Examiners (LLR)",
    sourceUrl: "https://llr.sc.gov/sw/",
    lastVerified: null,
  },
  {
    state: "South Dakota", stateCode: "SD", slug: "south-dakota", discipline: "social-work",
    requirementType: "hours", contactHours: 40, cycleYears: 2,
    summary: "South Dakota social workers must complete 40 hours of continuing education every 2 years.",
    details: "Verify current hours and any ethics minimum.",
    acceptsNationalAccreditation: true,
    boardName: "South Dakota Board of Social Work Examiners",
    sourceUrl: "https://dlr.sd.gov/bdcomm/socialwork/",
    lastVerified: null,
  },
  {
    state: "Tennessee", stateCode: "TN", slug: "tennessee", discipline: "social-work",
    requirementType: "hours", contactHours: 30, cycleYears: 2,
    summary: "Tennessee social workers must complete continuing education every 2 years, including ethics — verify the current hour requirement.",
    details: "Verify hours by level (LBSW/LMSW/LCSW; LCSW historically 30/2 with clinical minimums).",
    acceptsNationalAccreditation: true,
    boardName: "Tennessee Board of Social Worker Licensure",
    sourceUrl: "https://www.tn.gov/health/health-program-areas/health-professional-boards/sw-board.html",
    lastVerified: null,
  },
  {
    state: "Texas", stateCode: "TX", slug: "texas", discipline: "social-work",
    requirementType: "hours", contactHours: 30, cycleYears: 2,
    summary: "Texas social workers (LBSW, LMSW, LCSW) must complete 30 hours of continuing education every 2-year renewal period, including 6 hours of ethics and 3 hours on serving a distinct population.",
    mandatoryTopics: [
      { topic: "Ethics", hours: 6, frequency: "every renewal; counts within the 30" },
      { topic: "Competency serving a distinct population (cultural diversity)", hours: 3, frequency: "every renewal; counts within the 30" },
      { topic: "Human trafficking prevention (HHSC-approved course)", hours: 1, frequency: "every renewal — condition of renewal for licenses allowing direct patient care; may be claimed as 1 CE hour" },
      { topic: "Supervision (Council-approved supervisors only)", hours: 6, frequency: "every renewal, only if maintaining supervisor status; counts within the 30" },
    ],
    details: "22 TAC 781.501; requirements are identical for LBSW, LMSW, and LCSW. Effective January 1, 2024, at least half (15) of the 30 hours must come from a provider category listed in 781.501(f) — professional associations, universities, government entities, hospitals, or providers approved/endorsed by them (ASWB ACE- and NASW-approved providers qualify); the other 15 hours may come from any acceptable source. Up to 10 excess hours may carry forward one period. BHEC uses CE Broker as its official CE tracking system. The jurisprudence exam is an initial-licensure requirement, not a renewal one (passing it voluntarily may be claimed as 1 ethics hour).",
    acceptsNationalAccreditation: true,
    boardName: "Texas Behavioral Health Executive Council (Texas State Board of Social Worker Examiners)",
    sourceUrl: "https://bhec.texas.gov/texas-state-board-of-social-worker-examiners/renewing-a-social-work-license",
    lastVerified: "2026-07-30",
  },
  {
    state: "Utah", stateCode: "UT", slug: "utah", discipline: "social-work",
    requirementType: "hours", contactHours: 40, cycleYears: 2,
    summary: "Utah social workers must complete 40 hours of continuing education every 2 years, including ethics and suicide-prevention coursework.",
    mandatoryTopics: [
      { topic: "Ethics/law", hours: 6, frequency: "every renewal — verify" },
      { topic: "Suicide prevention", hours: 2, frequency: "every renewal — verify" },
    ],
    acceptsNationalAccreditation: true,
    boardName: "Utah Division of Professional Licensing — Social Worker Licensing Board",
    sourceUrl: "https://dopl.utah.gov/social-work/",
    lastVerified: null,
  },
  {
    state: "Vermont", stateCode: "VT", slug: "vermont", discipline: "social-work",
    requirementType: "hours", contactHours: 20, cycleYears: 2,
    summary: "Vermont social workers must complete 20 hours of continuing education every 2 years.",
    details: "Verify current hours and any ethics/suicide-prevention mandates.",
    acceptsNationalAccreditation: true,
    boardName: "Vermont Board of Social Work Examiners (OPR)",
    sourceUrl: "https://sos.vermont.gov/social-workers/",
    lastVerified: null,
  },
  {
    state: "Virginia", stateCode: "VA", slug: "virginia", discipline: "social-work",
    requirementType: "hours", contactHours: 30, cycleYears: 2,
    contactHoursByLevel: "30 (LCSW) · 15 (LBSW & LMSW)",
    summary: "Virginia LCSWs must complete 30 contact hours of continuing education every 2 years; LBSWs and LMSWs must complete 15.",
    details: "Hours fall into two categories: at least 20 of an LCSW's 30 (10 of 15 for LBSWs/LMSWs) must be Category I formally organized learning — which includes structured online courses from approved organizations — while Category II individual activities like unstructured self-study and professional reading are capped at 10 (or 5). Up to 2 hours may be earned by providing uncompensated social work services through a local health department or free clinic (3 volunteer hours = 1 CE hour). The Board can grant a one-year extension for good cause on written request before the renewal date.",
    mandatoryTopics: [
      { topic: "Ethics, standards of practice, or Virginia social work law (6 hrs LCSW / 3 hrs LBSW & LMSW)", frequency: "every renewal" },
    ],
    acceptsNationalAccreditation: true,
    accreditationNote: "Virginia's regulation expressly lists the Association of Social Work Boards as an approved Category I organization (18VAC140-20-105.B.1.d), so ASWB ACE-approved provider courses — including online courses — count as formal Category I learning with no delivery-format cap.",
    boardName: "Virginia Board of Social Work",
    sourceUrl: "https://law.lis.virginia.gov/admincode/title18/agency140/chapter20/section105/",
    lastVerified: "2026-08-14",
  },
  {
    // NOTE: 32 hours is correct per current WAC 246-809-630(3). Many CE vendors still
    // publish 36 (the pre-licensure figure / pre-amendment number). Do not "correct"
    // this back to 36.
    state: "Washington", stateCode: "WA", slug: "washington", discipline: "social-work",
    requirementType: "hours", contactHours: 32, cycleYears: 2,
    summary: "Washington LICSWs and LASWs must complete 32 hours of continuing education every 2-year reporting period (license renewal itself is annual, on your birthday).",
    details: "There is no cap on distance learning, but asynchronous courses must include a test of comprehension. Social worker associates (LSWAA and LSWAIC) are on a different track of 16 hours per year. Employer-sponsored training is capped at 26 hours per reporting period. The Department of Health does not pre-approve CE providers; courses must meet the standards in WAC 246-809-610 and be sponsored by industry-recognized organizations.",
    mandatoryTopics: [
      { topic: "Professional ethics and law", hours: 6, frequency: "every renewal" },
      { topic: "Professional roles and boundaries (separate from the ethics hours)", hours: 2, frequency: "every renewal" },
      { topic: "Suicide assessment, treatment, and management (from the DOH Model List)", hours: 6, frequency: "every 6 years" },
      { topic: "Health equity", hours: 2, frequency: "every 4 years" },
    ],
    acceptsNationalAccreditation: true,
    accreditationNote: "Washington doesn't pre-approve CE providers — courses from nationally recognized social work organizations, including ASWB ACE-approved providers, meet the rule's standards. One exception: the 6-hour suicide training must come from the Department of Health's Model List, so ACE approval alone does not satisfy that specific requirement.",
    boardName: "Washington State Department of Health",
    sourceUrl: "https://doh.wa.gov/licenses-permits-and-certificates/professions-new-renew-or-update/social-worker-and-social-worker-associate/continuing-education",
    lastVerified: "2026-08-14",
  },
  {
    state: "West Virginia", stateCode: "WV", slug: "west-virginia", discipline: "social-work",
    requirementType: "hours", contactHours: 25, cycleYears: 2,
    summary: "West Virginia social workers must complete 25 hours of continuing education every 2 years, including ethics.",
    details: "Verify current hours (25?) and the ethics/veterans mandates.",
    acceptsNationalAccreditation: true,
    boardName: "West Virginia Board of Social Work",
    sourceUrl: "https://socialworkboard.wv.gov/",
    lastVerified: null,
  },
  {
    state: "Wisconsin", stateCode: "WI", slug: "wisconsin", discipline: "social-work",
    requirementType: "hours", contactHours: 30, cycleYears: 2,
    summary: "Wisconsin social workers must complete 30 hours of continuing education every 2 years, including 4 hours of ethics.",
    details: "Verify ethics minimum (4 hrs boundaries/ethics?) and renewal deadline.",
    mandatoryTopics: [
      { topic: "Ethics and boundaries", hours: 4, frequency: "every renewal — verify" },
    ],
    acceptsNationalAccreditation: true,
    boardName: "Wisconsin Marriage and Family Therapy, Professional Counseling and Social Work Examining Board",
    sourceUrl: "https://dsps.wi.gov/Pages/Professions/SocialWorker/Default.aspx",
    lastVerified: null,
  },
  {
    state: "Wyoming", stateCode: "WY", slug: "wyoming", discipline: "social-work",
    requirementType: "hours", contactHours: 45, cycleYears: 2,
    summary: "Wyoming social workers must complete 45 hours of continuing education every 2 years.",
    details: "Verify current hours and any ethics minimum.",
    acceptsNationalAccreditation: true,
    boardName: "Wyoming Mental Health Professions Licensing Board",
    sourceUrl: "https://mentalhealth.wyo.gov/",
    lastVerified: null,
  },
  {
    state: "Washington, D.C.", stateCode: "DC", slug: "washington-dc", discipline: "social-work",
    requirementType: "hours", contactHours: 40, cycleYears: 2,
    summary: "D.C. social workers must complete 40 hours of continuing education every 2 years, including ethics and LGBTQ cultural-competency coursework.",
    mandatoryTopics: [
      { topic: "Ethics", hours: 6, frequency: "every renewal — verify" },
      { topic: "LGBTQ cultural competency", hours: 2, frequency: "every renewal — verify" },
      { topic: "Public health priorities (per DC Health)", frequency: "every renewal — verify current topics" },
    ],
    acceptsNationalAccreditation: true,
    boardName: "District of Columbia Board of Social Work",
    sourceUrl: "https://dchealth.dc.gov/service/social-work-licensing",
    lastVerified: null,
  },
];
